// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: stats/stats.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request Messages
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_stats_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatsRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetStatsRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type GetYearlyStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetYearlyStatsRequest) Reset() {
	*x = GetYearlyStatsRequest{}
	mi := &file_stats_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetYearlyStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetYearlyStatsRequest) ProtoMessage() {}

func (x *GetYearlyStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetYearlyStatsRequest.ProtoReflect.Descriptor instead.
func (*GetYearlyStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{1}
}

func (x *GetYearlyStatsRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type GetStatsByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Id            uint32                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsByIdRequest) Reset() {
	*x = GetStatsByIdRequest{}
	mi := &file_stats_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsByIdRequest) ProtoMessage() {}

func (x *GetStatsByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsByIdRequest.ProtoReflect.Descriptor instead.
func (*GetStatsByIdRequest) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatsByIdRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetStatsByIdRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *GetStatsByIdRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetYearlyStatsByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Id            uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetYearlyStatsByIdRequest) Reset() {
	*x = GetYearlyStatsByIdRequest{}
	mi := &file_stats_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetYearlyStatsByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetYearlyStatsByIdRequest) ProtoMessage() {}

func (x *GetYearlyStatsByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetYearlyStatsByIdRequest.ProtoReflect.Descriptor instead.
func (*GetYearlyStatsByIdRequest) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{3}
}

func (x *GetYearlyStatsByIdRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetYearlyStatsByIdRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetStatsByMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	MerchantId    uint32                 `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsByMerchantRequest) Reset() {
	*x = GetStatsByMerchantRequest{}
	mi := &file_stats_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsByMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsByMerchantRequest) ProtoMessage() {}

func (x *GetStatsByMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsByMerchantRequest.ProtoReflect.Descriptor instead.
func (*GetStatsByMerchantRequest) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatsByMerchantRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetStatsByMerchantRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *GetStatsByMerchantRequest) GetMerchantId() uint32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type GetYearlyStatsByMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	MerchantId    uint32                 `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetYearlyStatsByMerchantRequest) Reset() {
	*x = GetYearlyStatsByMerchantRequest{}
	mi := &file_stats_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetYearlyStatsByMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetYearlyStatsByMerchantRequest) ProtoMessage() {}

func (x *GetYearlyStatsByMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetYearlyStatsByMerchantRequest.ProtoReflect.Descriptor instead.
func (*GetYearlyStatsByMerchantRequest) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{5}
}

func (x *GetYearlyStatsByMerchantRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetYearlyStatsByMerchantRequest) GetMerchantId() uint32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

// Response Messages - Category
type MonthlyPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MonthlyPriceItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyPriceResponse) Reset() {
	*x = MonthlyPriceResponse{}
	mi := &file_stats_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyPriceResponse) ProtoMessage() {}

func (x *MonthlyPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyPriceResponse.ProtoReflect.Descriptor instead.
func (*MonthlyPriceResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{6}
}

func (x *MonthlyPriceResponse) GetItems() []*MonthlyPriceItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type MonthlyPriceItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	TotalPrice    uint64                 `protobuf:"varint,2,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyPriceItem) Reset() {
	*x = MonthlyPriceItem{}
	mi := &file_stats_stats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyPriceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyPriceItem) ProtoMessage() {}

func (x *MonthlyPriceItem) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyPriceItem.ProtoReflect.Descriptor instead.
func (*MonthlyPriceItem) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{7}
}

func (x *MonthlyPriceItem) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthlyPriceItem) GetTotalPrice() uint64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type YearlyPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*YearlyPriceItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearlyPriceResponse) Reset() {
	*x = YearlyPriceResponse{}
	mi := &file_stats_stats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearlyPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearlyPriceResponse) ProtoMessage() {}

func (x *YearlyPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearlyPriceResponse.ProtoReflect.Descriptor instead.
func (*YearlyPriceResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{8}
}

func (x *YearlyPriceResponse) GetItems() []*YearlyPriceItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type YearlyPriceItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalPrice    uint64                 `protobuf:"varint,2,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearlyPriceItem) Reset() {
	*x = YearlyPriceItem{}
	mi := &file_stats_stats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearlyPriceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearlyPriceItem) ProtoMessage() {}

func (x *YearlyPriceItem) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearlyPriceItem.ProtoReflect.Descriptor instead.
func (*YearlyPriceItem) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{9}
}

func (x *YearlyPriceItem) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *YearlyPriceItem) GetTotalPrice() uint64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type MonthlyCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MonthlyCategoryItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyCategoryResponse) Reset() {
	*x = MonthlyCategoryResponse{}
	mi := &file_stats_stats_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyCategoryResponse) ProtoMessage() {}

func (x *MonthlyCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyCategoryResponse.ProtoReflect.Descriptor instead.
func (*MonthlyCategoryResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{10}
}

func (x *MonthlyCategoryResponse) GetItems() []*MonthlyCategoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type MonthlyCategoryItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Month             string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	CategoryId        uint32                 `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TotalViews        uint32                 `protobuf:"varint,3,opt,name=total_views,json=totalViews,proto3" json:"total_views,omitempty"`
	TotalTransactions uint32                 `protobuf:"varint,4,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MonthlyCategoryItem) Reset() {
	*x = MonthlyCategoryItem{}
	mi := &file_stats_stats_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyCategoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyCategoryItem) ProtoMessage() {}

func (x *MonthlyCategoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyCategoryItem.ProtoReflect.Descriptor instead.
func (*MonthlyCategoryItem) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{11}
}

func (x *MonthlyCategoryItem) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthlyCategoryItem) GetCategoryId() uint32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *MonthlyCategoryItem) GetTotalViews() uint32 {
	if x != nil {
		return x.TotalViews
	}
	return 0
}

func (x *MonthlyCategoryItem) GetTotalTransactions() uint32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

type YearlyCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*YearlyCategoryItem  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearlyCategoryResponse) Reset() {
	*x = YearlyCategoryResponse{}
	mi := &file_stats_stats_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearlyCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearlyCategoryResponse) ProtoMessage() {}

func (x *YearlyCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearlyCategoryResponse.ProtoReflect.Descriptor instead.
func (*YearlyCategoryResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{12}
}

func (x *YearlyCategoryResponse) GetItems() []*YearlyCategoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type YearlyCategoryItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Year              int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	CategoryId        uint32                 `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TotalViews        uint32                 `protobuf:"varint,3,opt,name=total_views,json=totalViews,proto3" json:"total_views,omitempty"`
	TotalTransactions uint32                 `protobuf:"varint,4,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *YearlyCategoryItem) Reset() {
	*x = YearlyCategoryItem{}
	mi := &file_stats_stats_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearlyCategoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearlyCategoryItem) ProtoMessage() {}

func (x *YearlyCategoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearlyCategoryItem.ProtoReflect.Descriptor instead.
func (*YearlyCategoryItem) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{13}
}

func (x *YearlyCategoryItem) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *YearlyCategoryItem) GetCategoryId() uint32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *YearlyCategoryItem) GetTotalViews() uint32 {
	if x != nil {
		return x.TotalViews
	}
	return 0
}

func (x *YearlyCategoryItem) GetTotalTransactions() uint32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

// Response Messages - Order
type MonthlyRevenueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MonthlyRevenueItem  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyRevenueResponse) Reset() {
	*x = MonthlyRevenueResponse{}
	mi := &file_stats_stats_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyRevenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyRevenueResponse) ProtoMessage() {}

func (x *MonthlyRevenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyRevenueResponse.ProtoReflect.Descriptor instead.
func (*MonthlyRevenueResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{14}
}

func (x *MonthlyRevenueResponse) GetItems() []*MonthlyRevenueItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type MonthlyRevenueItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	TotalRevenue  uint64                 `protobuf:"varint,2,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyRevenueItem) Reset() {
	*x = MonthlyRevenueItem{}
	mi := &file_stats_stats_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyRevenueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyRevenueItem) ProtoMessage() {}

func (x *MonthlyRevenueItem) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyRevenueItem.ProtoReflect.Descriptor instead.
func (*MonthlyRevenueItem) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{15}
}

func (x *MonthlyRevenueItem) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthlyRevenueItem) GetTotalRevenue() uint64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

type YearlyRevenueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*YearlyRevenueItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearlyRevenueResponse) Reset() {
	*x = YearlyRevenueResponse{}
	mi := &file_stats_stats_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearlyRevenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearlyRevenueResponse) ProtoMessage() {}

func (x *YearlyRevenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearlyRevenueResponse.ProtoReflect.Descriptor instead.
func (*YearlyRevenueResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{16}
}

func (x *YearlyRevenueResponse) GetItems() []*YearlyRevenueItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type YearlyRevenueItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalRevenue  uint64                 `protobuf:"varint,2,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearlyRevenueItem) Reset() {
	*x = YearlyRevenueItem{}
	mi := &file_stats_stats_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearlyRevenueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearlyRevenueItem) ProtoMessage() {}

func (x *YearlyRevenueItem) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearlyRevenueItem.ProtoReflect.Descriptor instead.
func (*YearlyRevenueItem) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{17}
}

func (x *YearlyRevenueItem) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *YearlyRevenueItem) GetTotalRevenue() uint64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

type MonthlyOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MonthlyOrderItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyOrderResponse) Reset() {
	*x = MonthlyOrderResponse{}
	mi := &file_stats_stats_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyOrderResponse) ProtoMessage() {}

func (x *MonthlyOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyOrderResponse.ProtoReflect.Descriptor instead.
func (*MonthlyOrderResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{18}
}

func (x *MonthlyOrderResponse) GetItems() []*MonthlyOrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type MonthlyOrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	TotalOrders   uint32                 `protobuf:"varint,2,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyOrderItem) Reset() {
	*x = MonthlyOrderItem{}
	mi := &file_stats_stats_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyOrderItem) ProtoMessage() {}

func (x *MonthlyOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyOrderItem.ProtoReflect.Descriptor instead.
func (*MonthlyOrderItem) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{19}
}

func (x *MonthlyOrderItem) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthlyOrderItem) GetTotalOrders() uint32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

type YearlyOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*YearlyOrderItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearlyOrderResponse) Reset() {
	*x = YearlyOrderResponse{}
	mi := &file_stats_stats_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearlyOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearlyOrderResponse) ProtoMessage() {}

func (x *YearlyOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearlyOrderResponse.ProtoReflect.Descriptor instead.
func (*YearlyOrderResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{20}
}

func (x *YearlyOrderResponse) GetItems() []*YearlyOrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type YearlyOrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalOrders   uint32                 `protobuf:"varint,2,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearlyOrderItem) Reset() {
	*x = YearlyOrderItem{}
	mi := &file_stats_stats_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearlyOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearlyOrderItem) ProtoMessage() {}

func (x *YearlyOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearlyOrderItem.ProtoReflect.Descriptor instead.
func (*YearlyOrderItem) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{21}
}

func (x *YearlyOrderItem) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *YearlyOrderItem) GetTotalOrders() uint32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

// Response Messages - Transaction
type MonthlyAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MonthlyAmountItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyAmountResponse) Reset() {
	*x = MonthlyAmountResponse{}
	mi := &file_stats_stats_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyAmountResponse) ProtoMessage() {}

func (x *MonthlyAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyAmountResponse.ProtoReflect.Descriptor instead.
func (*MonthlyAmountResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{22}
}

func (x *MonthlyAmountResponse) GetItems() []*MonthlyAmountItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type MonthlyAmountItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	TotalAmount   uint64                 `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyAmountItem) Reset() {
	*x = MonthlyAmountItem{}
	mi := &file_stats_stats_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyAmountItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyAmountItem) ProtoMessage() {}

func (x *MonthlyAmountItem) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyAmountItem.ProtoReflect.Descriptor instead.
func (*MonthlyAmountItem) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{23}
}

func (x *MonthlyAmountItem) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthlyAmountItem) GetTotalAmount() uint64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type YearlyAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*YearlyAmountItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearlyAmountResponse) Reset() {
	*x = YearlyAmountResponse{}
	mi := &file_stats_stats_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearlyAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearlyAmountResponse) ProtoMessage() {}

func (x *YearlyAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearlyAmountResponse.ProtoReflect.Descriptor instead.
func (*YearlyAmountResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{24}
}

func (x *YearlyAmountResponse) GetItems() []*YearlyAmountItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type YearlyAmountItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalAmount   uint64                 `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearlyAmountItem) Reset() {
	*x = YearlyAmountItem{}
	mi := &file_stats_stats_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearlyAmountItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearlyAmountItem) ProtoMessage() {}

func (x *YearlyAmountItem) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearlyAmountItem.ProtoReflect.Descriptor instead.
func (*YearlyAmountItem) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{25}
}

func (x *YearlyAmountItem) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *YearlyAmountItem) GetTotalAmount() uint64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type MonthlyMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MonthlyMethodItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyMethodResponse) Reset() {
	*x = MonthlyMethodResponse{}
	mi := &file_stats_stats_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyMethodResponse) ProtoMessage() {}

func (x *MonthlyMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyMethodResponse.ProtoReflect.Descriptor instead.
func (*MonthlyMethodResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{26}
}

func (x *MonthlyMethodResponse) GetItems() []*MonthlyMethodItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type MonthlyMethodItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Month             string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	PaymentMethod     string                 `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TotalTransactions uint32                 `protobuf:"varint,3,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalAmount       uint64                 `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MonthlyMethodItem) Reset() {
	*x = MonthlyMethodItem{}
	mi := &file_stats_stats_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyMethodItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyMethodItem) ProtoMessage() {}

func (x *MonthlyMethodItem) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyMethodItem.ProtoReflect.Descriptor instead.
func (*MonthlyMethodItem) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{27}
}

func (x *MonthlyMethodItem) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthlyMethodItem) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *MonthlyMethodItem) GetTotalTransactions() uint32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *MonthlyMethodItem) GetTotalAmount() uint64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type YearlyMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*YearlyMethodItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearlyMethodResponse) Reset() {
	*x = YearlyMethodResponse{}
	mi := &file_stats_stats_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearlyMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearlyMethodResponse) ProtoMessage() {}

func (x *YearlyMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearlyMethodResponse.ProtoReflect.Descriptor instead.
func (*YearlyMethodResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{28}
}

func (x *YearlyMethodResponse) GetItems() []*YearlyMethodItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type YearlyMethodItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Year              int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	PaymentMethod     string                 `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TotalTransactions uint32                 `protobuf:"varint,3,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalAmount       uint64                 `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *YearlyMethodItem) Reset() {
	*x = YearlyMethodItem{}
	mi := &file_stats_stats_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearlyMethodItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearlyMethodItem) ProtoMessage() {}

func (x *YearlyMethodItem) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearlyMethodItem.ProtoReflect.Descriptor instead.
func (*YearlyMethodItem) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{29}
}

func (x *YearlyMethodItem) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *YearlyMethodItem) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *YearlyMethodItem) GetTotalTransactions() uint32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *YearlyMethodItem) GetTotalAmount() uint64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

var File_stats_stats_proto protoreflect.FileDescriptor

const file_stats_stats_proto_rawDesc = "" +
	"\n" +
	"\x11stats/stats.proto\x12\x05stats\";\n" +
	"\x0fGetStatsRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\"+\n" +
	"\x15GetYearlyStatsRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\"O\n" +
	"\x13GetStatsByIdRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\rR\x02id\"?\n" +
	"\x19GetYearlyStatsByIdRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\"f\n" +
	"\x19GetStatsByMerchantRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\rR\n" +
	"merchantId\"V\n" +
	"\x1fGetYearlyStatsByMerchantRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\rR\n" +
	"merchantId\"E\n" +
	"\x14MonthlyPriceResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.stats.MonthlyPriceItemR\x05items\"I\n" +
	"\x10MonthlyPriceItem\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x1f\n" +
	"\vtotal_price\x18\x02 \x01(\x04R\n" +
	"totalPrice\"C\n" +
	"\x13YearlyPriceResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.stats.YearlyPriceItemR\x05items\"F\n" +
	"\x0fYearlyPriceItem\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x1f\n" +
	"\vtotal_price\x18\x02 \x01(\x04R\n" +
	"totalPrice\"K\n" +
	"\x17MonthlyCategoryResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.stats.MonthlyCategoryItemR\x05items\"\x9c\x01\n" +
	"\x13MonthlyCategoryItem\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\rR\n" +
	"categoryId\x12\x1f\n" +
	"\vtotal_views\x18\x03 \x01(\rR\n" +
	"totalViews\x12-\n" +
	"\x12total_transactions\x18\x04 \x01(\rR\x11totalTransactions\"I\n" +
	"\x16YearlyCategoryResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.stats.YearlyCategoryItemR\x05items\"\x99\x01\n" +
	"\x12YearlyCategoryItem\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\rR\n" +
	"categoryId\x12\x1f\n" +
	"\vtotal_views\x18\x03 \x01(\rR\n" +
	"totalViews\x12-\n" +
	"\x12total_transactions\x18\x04 \x01(\rR\x11totalTransactions\"I\n" +
	"\x16MonthlyRevenueResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.stats.MonthlyRevenueItemR\x05items\"O\n" +
	"\x12MonthlyRevenueItem\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12#\n" +
	"\rtotal_revenue\x18\x02 \x01(\x04R\ftotalRevenue\"G\n" +
	"\x15YearlyRevenueResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.stats.YearlyRevenueItemR\x05items\"L\n" +
	"\x11YearlyRevenueItem\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12#\n" +
	"\rtotal_revenue\x18\x02 \x01(\x04R\ftotalRevenue\"E\n" +
	"\x14MonthlyOrderResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.stats.MonthlyOrderItemR\x05items\"K\n" +
	"\x10MonthlyOrderItem\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12!\n" +
	"\ftotal_orders\x18\x02 \x01(\rR\vtotalOrders\"C\n" +
	"\x13YearlyOrderResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.stats.YearlyOrderItemR\x05items\"H\n" +
	"\x0fYearlyOrderItem\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12!\n" +
	"\ftotal_orders\x18\x02 \x01(\rR\vtotalOrders\"G\n" +
	"\x15MonthlyAmountResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.stats.MonthlyAmountItemR\x05items\"L\n" +
	"\x11MonthlyAmountItem\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x04R\vtotalAmount\"E\n" +
	"\x14YearlyAmountResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.stats.YearlyAmountItemR\x05items\"I\n" +
	"\x10YearlyAmountItem\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x04R\vtotalAmount\"G\n" +
	"\x15MonthlyMethodResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.stats.MonthlyMethodItemR\x05items\"\xa2\x01\n" +
	"\x11MonthlyMethodItem\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\x12-\n" +
	"\x12total_transactions\x18\x03 \x01(\rR\x11totalTransactions\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x04R\vtotalAmount\"E\n" +
	"\x14YearlyMethodResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.stats.YearlyMethodItemR\x05items\"\x9f\x01\n" +
	"\x10YearlyMethodItem\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\x12-\n" +
	"\x12total_transactions\x18\x03 \x01(\rR\x11totalTransactions\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x04R\vtotalAmount2\x8d\x1a\n" +
	"\fStatsService\x12K\n" +
	"\x14GetMonthlyTotalPrice\x12\x16.stats.GetStatsRequest\x1a\x1b.stats.MonthlyPriceResponse\x12P\n" +
	"\x14GetYearlyTotalPrices\x12\x1c.stats.GetYearlyStatsRequest\x1a\x1a.stats.YearlyPriceResponse\x12M\n" +
	"\rGetMonthPrice\x12\x1c.stats.GetYearlyStatsRequest\x1a\x1e.stats.MonthlyCategoryResponse\x12K\n" +
	"\fGetYearPrice\x12\x1c.stats.GetYearlyStatsRequest\x1a\x1d.stats.YearlyCategoryResponse\x12S\n" +
	"\x18GetMonthlyTotalPriceById\x12\x1a.stats.GetStatsByIdRequest\x1a\x1b.stats.MonthlyPriceResponse\x12X\n" +
	"\x18GetYearlyTotalPricesById\x12 .stats.GetYearlyStatsByIdRequest\x1a\x1a.stats.YearlyPriceResponse\x12O\n" +
	"\x11GetMonthPriceById\x12\x1a.stats.GetStatsByIdRequest\x1a\x1e.stats.MonthlyCategoryResponse\x12S\n" +
	"\x10GetYearPriceById\x12 .stats.GetYearlyStatsByIdRequest\x1a\x1d.stats.YearlyCategoryResponse\x12_\n" +
	"\x1eGetMonthlyTotalPriceByMerchant\x12 .stats.GetStatsByMerchantRequest\x1a\x1b.stats.MonthlyPriceResponse\x12d\n" +
	"\x1eGetYearlyTotalPricesByMerchant\x12&.stats.GetYearlyStatsByMerchantRequest\x1a\x1a.stats.YearlyPriceResponse\x12[\n" +
	"\x17GetMonthPriceByMerchant\x12 .stats.GetStatsByMerchantRequest\x1a\x1e.stats.MonthlyCategoryResponse\x12_\n" +
	"\x16GetYearPriceByMerchant\x12&.stats.GetYearlyStatsByMerchantRequest\x1a\x1d.stats.YearlyCategoryResponse\x12O\n" +
	"\x16GetMonthlyTotalRevenue\x12\x16.stats.GetStatsRequest\x1a\x1d.stats.MonthlyRevenueResponse\x12S\n" +
	"\x15GetYearlyTotalRevenue\x12\x1c.stats.GetYearlyStatsRequest\x1a\x1c.stats.YearlyRevenueResponse\x12L\n" +
	"\x0fGetMonthlyOrder\x12\x1c.stats.GetYearlyStatsRequest\x1a\x1b.stats.MonthlyOrderResponse\x12J\n" +
	"\x0eGetYearlyOrder\x12\x1c.stats.GetYearlyStatsRequest\x1a\x1a.stats.YearlyOrderResponse\x12c\n" +
	" GetMonthlyTotalRevenueByMerchant\x12 .stats.GetStatsByMerchantRequest\x1a\x1d.stats.MonthlyRevenueResponse\x12g\n" +
	"\x1fGetYearlyTotalRevenueByMerchant\x12&.stats.GetYearlyStatsByMerchantRequest\x1a\x1c.stats.YearlyRevenueResponse\x12Z\n" +
	"\x19GetMonthlyOrderByMerchant\x12 .stats.GetStatsByMerchantRequest\x1a\x1b.stats.MonthlyOrderResponse\x12^\n" +
	"\x18GetYearlyOrderByMerchant\x12&.stats.GetYearlyStatsByMerchantRequest\x1a\x1a.stats.YearlyOrderResponse\x12O\n" +
	"\x17GetMonthlyAmountSuccess\x12\x16.stats.GetStatsRequest\x1a\x1c.stats.MonthlyAmountResponse\x12S\n" +
	"\x16GetYearlyAmountSuccess\x12\x1c.stats.GetYearlyStatsRequest\x1a\x1b.stats.YearlyAmountResponse\x12N\n" +
	"\x16GetMonthlyAmountFailed\x12\x16.stats.GetStatsRequest\x1a\x1c.stats.MonthlyAmountResponse\x12R\n" +
	"\x15GetYearlyAmountFailed\x12\x1c.stats.GetYearlyStatsRequest\x1a\x1b.stats.YearlyAmountResponse\x12Z\n" +
	"\"GetMonthlyTransactionMethodSuccess\x12\x16.stats.GetStatsRequest\x1a\x1c.stats.MonthlyMethodResponse\x12^\n" +
	"!GetYearlyTransactionMethodSuccess\x12\x1c.stats.GetYearlyStatsRequest\x1a\x1b.stats.YearlyMethodResponse\x12Y\n" +
	"!GetMonthlyTransactionMethodFailed\x12\x16.stats.GetStatsRequest\x1a\x1c.stats.MonthlyMethodResponse\x12]\n" +
	" GetYearlyTransactionMethodFailed\x12\x1c.stats.GetYearlyStatsRequest\x1a\x1b.stats.YearlyMethodResponse\x12c\n" +
	"!GetMonthlyAmountSuccessByMerchant\x12 .stats.GetStatsByMerchantRequest\x1a\x1c.stats.MonthlyAmountResponse\x12g\n" +
	" GetYearlyAmountSuccessByMerchant\x12&.stats.GetYearlyStatsByMerchantRequest\x1a\x1b.stats.YearlyAmountResponse\x12b\n" +
	" GetMonthlyAmountFailedByMerchant\x12 .stats.GetStatsByMerchantRequest\x1a\x1c.stats.MonthlyAmountResponse\x12f\n" +
	"\x1fGetYearlyAmountFailedByMerchant\x12&.stats.GetYearlyStatsByMerchantRequest\x1a\x1b.stats.YearlyAmountResponse\x12n\n" +
	",GetMonthlyTransactionMethodByMerchantSuccess\x12 .stats.GetStatsByMerchantRequest\x1a\x1c.stats.MonthlyMethodResponse\x12r\n" +
	"+GetYearlyTransactionMethodByMerchantSuccess\x12&.stats.GetYearlyStatsByMerchantRequest\x1a\x1b.stats.YearlyMethodResponse\x12m\n" +
	"+GetMonthlyTransactionMethodByMerchantFailed\x12 .stats.GetStatsByMerchantRequest\x1a\x1c.stats.MonthlyMethodResponse\x12q\n" +
	"*GetYearlyTransactionMethodByMerchantFailed\x12&.stats.GetYearlyStatsByMerchantRequest\x1a\x1b.stats.YearlyMethodResponseB:Z8github.com/MamangRust/microservice-ecommerce-shared/pb/statsb\x06proto3"

var (
	file_stats_stats_proto_rawDescOnce sync.Once
	file_stats_stats_proto_rawDescData []byte
)

func file_stats_stats_proto_rawDescGZIP() []byte {
	file_stats_stats_proto_rawDescOnce.Do(func() {
		file_stats_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_stats_proto_rawDesc), len(file_stats_stats_proto_rawDesc)))
	})
	return file_stats_stats_proto_rawDescData
}

var file_stats_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_stats_stats_proto_goTypes = []any{
	(*GetStatsRequest)(nil),                 // 0: stats.GetStatsRequest
	(*GetYearlyStatsRequest)(nil),           // 1: stats.GetYearlyStatsRequest
	(*GetStatsByIdRequest)(nil),             // 2: stats.GetStatsByIdRequest
	(*GetYearlyStatsByIdRequest)(nil),       // 3: stats.GetYearlyStatsByIdRequest
	(*GetStatsByMerchantRequest)(nil),       // 4: stats.GetStatsByMerchantRequest
	(*GetYearlyStatsByMerchantRequest)(nil), // 5: stats.GetYearlyStatsByMerchantRequest
	(*MonthlyPriceResponse)(nil),            // 6: stats.MonthlyPriceResponse
	(*MonthlyPriceItem)(nil),                // 7: stats.MonthlyPriceItem
	(*YearlyPriceResponse)(nil),             // 8: stats.YearlyPriceResponse
	(*YearlyPriceItem)(nil),                 // 9: stats.YearlyPriceItem
	(*MonthlyCategoryResponse)(nil),         // 10: stats.MonthlyCategoryResponse
	(*MonthlyCategoryItem)(nil),             // 11: stats.MonthlyCategoryItem
	(*YearlyCategoryResponse)(nil),          // 12: stats.YearlyCategoryResponse
	(*YearlyCategoryItem)(nil),              // 13: stats.YearlyCategoryItem
	(*MonthlyRevenueResponse)(nil),          // 14: stats.MonthlyRevenueResponse
	(*MonthlyRevenueItem)(nil),              // 15: stats.MonthlyRevenueItem
	(*YearlyRevenueResponse)(nil),           // 16: stats.YearlyRevenueResponse
	(*YearlyRevenueItem)(nil),               // 17: stats.YearlyRevenueItem
	(*MonthlyOrderResponse)(nil),            // 18: stats.MonthlyOrderResponse
	(*MonthlyOrderItem)(nil),                // 19: stats.MonthlyOrderItem
	(*YearlyOrderResponse)(nil),             // 20: stats.YearlyOrderResponse
	(*YearlyOrderItem)(nil),                 // 21: stats.YearlyOrderItem
	(*MonthlyAmountResponse)(nil),           // 22: stats.MonthlyAmountResponse
	(*MonthlyAmountItem)(nil),               // 23: stats.MonthlyAmountItem
	(*YearlyAmountResponse)(nil),            // 24: stats.YearlyAmountResponse
	(*YearlyAmountItem)(nil),                // 25: stats.YearlyAmountItem
	(*MonthlyMethodResponse)(nil),           // 26: stats.MonthlyMethodResponse
	(*MonthlyMethodItem)(nil),               // 27: stats.MonthlyMethodItem
	(*YearlyMethodResponse)(nil),            // 28: stats.YearlyMethodResponse
	(*YearlyMethodItem)(nil),                // 29: stats.YearlyMethodItem
}
var file_stats_stats_proto_depIdxs = []int32{
	7,  // 0: stats.MonthlyPriceResponse.items:type_name -> stats.MonthlyPriceItem
	9,  // 1: stats.YearlyPriceResponse.items:type_name -> stats.YearlyPriceItem
	11, // 2: stats.MonthlyCategoryResponse.items:type_name -> stats.MonthlyCategoryItem
	13, // 3: stats.YearlyCategoryResponse.items:type_name -> stats.YearlyCategoryItem
	15, // 4: stats.MonthlyRevenueResponse.items:type_name -> stats.MonthlyRevenueItem
	17, // 5: stats.YearlyRevenueResponse.items:type_name -> stats.YearlyRevenueItem
	19, // 6: stats.MonthlyOrderResponse.items:type_name -> stats.MonthlyOrderItem
	21, // 7: stats.YearlyOrderResponse.items:type_name -> stats.YearlyOrderItem
	23, // 8: stats.MonthlyAmountResponse.items:type_name -> stats.MonthlyAmountItem
	25, // 9: stats.YearlyAmountResponse.items:type_name -> stats.YearlyAmountItem
	27, // 10: stats.MonthlyMethodResponse.items:type_name -> stats.MonthlyMethodItem
	29, // 11: stats.YearlyMethodResponse.items:type_name -> stats.YearlyMethodItem
	0,  // 12: stats.StatsService.GetMonthlyTotalPrice:input_type -> stats.GetStatsRequest
	1,  // 13: stats.StatsService.GetYearlyTotalPrices:input_type -> stats.GetYearlyStatsRequest
	1,  // 14: stats.StatsService.GetMonthPrice:input_type -> stats.GetYearlyStatsRequest
	1,  // 15: stats.StatsService.GetYearPrice:input_type -> stats.GetYearlyStatsRequest
	2,  // 16: stats.StatsService.GetMonthlyTotalPriceById:input_type -> stats.GetStatsByIdRequest
	3,  // 17: stats.StatsService.GetYearlyTotalPricesById:input_type -> stats.GetYearlyStatsByIdRequest
	2,  // 18: stats.StatsService.GetMonthPriceById:input_type -> stats.GetStatsByIdRequest
	3,  // 19: stats.StatsService.GetYearPriceById:input_type -> stats.GetYearlyStatsByIdRequest
	4,  // 20: stats.StatsService.GetMonthlyTotalPriceByMerchant:input_type -> stats.GetStatsByMerchantRequest
	5,  // 21: stats.StatsService.GetYearlyTotalPricesByMerchant:input_type -> stats.GetYearlyStatsByMerchantRequest
	4,  // 22: stats.StatsService.GetMonthPriceByMerchant:input_type -> stats.GetStatsByMerchantRequest
	5,  // 23: stats.StatsService.GetYearPriceByMerchant:input_type -> stats.GetYearlyStatsByMerchantRequest
	0,  // 24: stats.StatsService.GetMonthlyTotalRevenue:input_type -> stats.GetStatsRequest
	1,  // 25: stats.StatsService.GetYearlyTotalRevenue:input_type -> stats.GetYearlyStatsRequest
	1,  // 26: stats.StatsService.GetMonthlyOrder:input_type -> stats.GetYearlyStatsRequest
	1,  // 27: stats.StatsService.GetYearlyOrder:input_type -> stats.GetYearlyStatsRequest
	4,  // 28: stats.StatsService.GetMonthlyTotalRevenueByMerchant:input_type -> stats.GetStatsByMerchantRequest
	5,  // 29: stats.StatsService.GetYearlyTotalRevenueByMerchant:input_type -> stats.GetYearlyStatsByMerchantRequest
	4,  // 30: stats.StatsService.GetMonthlyOrderByMerchant:input_type -> stats.GetStatsByMerchantRequest
	5,  // 31: stats.StatsService.GetYearlyOrderByMerchant:input_type -> stats.GetYearlyStatsByMerchantRequest
	0,  // 32: stats.StatsService.GetMonthlyAmountSuccess:input_type -> stats.GetStatsRequest
	1,  // 33: stats.StatsService.GetYearlyAmountSuccess:input_type -> stats.GetYearlyStatsRequest
	0,  // 34: stats.StatsService.GetMonthlyAmountFailed:input_type -> stats.GetStatsRequest
	1,  // 35: stats.StatsService.GetYearlyAmountFailed:input_type -> stats.GetYearlyStatsRequest
	0,  // 36: stats.StatsService.GetMonthlyTransactionMethodSuccess:input_type -> stats.GetStatsRequest
	1,  // 37: stats.StatsService.GetYearlyTransactionMethodSuccess:input_type -> stats.GetYearlyStatsRequest
	0,  // 38: stats.StatsService.GetMonthlyTransactionMethodFailed:input_type -> stats.GetStatsRequest
	1,  // 39: stats.StatsService.GetYearlyTransactionMethodFailed:input_type -> stats.GetYearlyStatsRequest
	4,  // 40: stats.StatsService.GetMonthlyAmountSuccessByMerchant:input_type -> stats.GetStatsByMerchantRequest
	5,  // 41: stats.StatsService.GetYearlyAmountSuccessByMerchant:input_type -> stats.GetYearlyStatsByMerchantRequest
	4,  // 42: stats.StatsService.GetMonthlyAmountFailedByMerchant:input_type -> stats.GetStatsByMerchantRequest
	5,  // 43: stats.StatsService.GetYearlyAmountFailedByMerchant:input_type -> stats.GetYearlyStatsByMerchantRequest
	4,  // 44: stats.StatsService.GetMonthlyTransactionMethodByMerchantSuccess:input_type -> stats.GetStatsByMerchantRequest
	5,  // 45: stats.StatsService.GetYearlyTransactionMethodByMerchantSuccess:input_type -> stats.GetYearlyStatsByMerchantRequest
	4,  // 46: stats.StatsService.GetMonthlyTransactionMethodByMerchantFailed:input_type -> stats.GetStatsByMerchantRequest
	5,  // 47: stats.StatsService.GetYearlyTransactionMethodByMerchantFailed:input_type -> stats.GetYearlyStatsByMerchantRequest
	6,  // 48: stats.StatsService.GetMonthlyTotalPrice:output_type -> stats.MonthlyPriceResponse
	8,  // 49: stats.StatsService.GetYearlyTotalPrices:output_type -> stats.YearlyPriceResponse
	10, // 50: stats.StatsService.GetMonthPrice:output_type -> stats.MonthlyCategoryResponse
	12, // 51: stats.StatsService.GetYearPrice:output_type -> stats.YearlyCategoryResponse
	6,  // 52: stats.StatsService.GetMonthlyTotalPriceById:output_type -> stats.MonthlyPriceResponse
	8,  // 53: stats.StatsService.GetYearlyTotalPricesById:output_type -> stats.YearlyPriceResponse
	10, // 54: stats.StatsService.GetMonthPriceById:output_type -> stats.MonthlyCategoryResponse
	12, // 55: stats.StatsService.GetYearPriceById:output_type -> stats.YearlyCategoryResponse
	6,  // 56: stats.StatsService.GetMonthlyTotalPriceByMerchant:output_type -> stats.MonthlyPriceResponse
	8,  // 57: stats.StatsService.GetYearlyTotalPricesByMerchant:output_type -> stats.YearlyPriceResponse
	10, // 58: stats.StatsService.GetMonthPriceByMerchant:output_type -> stats.MonthlyCategoryResponse
	12, // 59: stats.StatsService.GetYearPriceByMerchant:output_type -> stats.YearlyCategoryResponse
	14, // 60: stats.StatsService.GetMonthlyTotalRevenue:output_type -> stats.MonthlyRevenueResponse
	16, // 61: stats.StatsService.GetYearlyTotalRevenue:output_type -> stats.YearlyRevenueResponse
	18, // 62: stats.StatsService.GetMonthlyOrder:output_type -> stats.MonthlyOrderResponse
	20, // 63: stats.StatsService.GetYearlyOrder:output_type -> stats.YearlyOrderResponse
	14, // 64: stats.StatsService.GetMonthlyTotalRevenueByMerchant:output_type -> stats.MonthlyRevenueResponse
	16, // 65: stats.StatsService.GetYearlyTotalRevenueByMerchant:output_type -> stats.YearlyRevenueResponse
	18, // 66: stats.StatsService.GetMonthlyOrderByMerchant:output_type -> stats.MonthlyOrderResponse
	20, // 67: stats.StatsService.GetYearlyOrderByMerchant:output_type -> stats.YearlyOrderResponse
	22, // 68: stats.StatsService.GetMonthlyAmountSuccess:output_type -> stats.MonthlyAmountResponse
	24, // 69: stats.StatsService.GetYearlyAmountSuccess:output_type -> stats.YearlyAmountResponse
	22, // 70: stats.StatsService.GetMonthlyAmountFailed:output_type -> stats.MonthlyAmountResponse
	24, // 71: stats.StatsService.GetYearlyAmountFailed:output_type -> stats.YearlyAmountResponse
	26, // 72: stats.StatsService.GetMonthlyTransactionMethodSuccess:output_type -> stats.MonthlyMethodResponse
	28, // 73: stats.StatsService.GetYearlyTransactionMethodSuccess:output_type -> stats.YearlyMethodResponse
	26, // 74: stats.StatsService.GetMonthlyTransactionMethodFailed:output_type -> stats.MonthlyMethodResponse
	28, // 75: stats.StatsService.GetYearlyTransactionMethodFailed:output_type -> stats.YearlyMethodResponse
	22, // 76: stats.StatsService.GetMonthlyAmountSuccessByMerchant:output_type -> stats.MonthlyAmountResponse
	24, // 77: stats.StatsService.GetYearlyAmountSuccessByMerchant:output_type -> stats.YearlyAmountResponse
	22, // 78: stats.StatsService.GetMonthlyAmountFailedByMerchant:output_type -> stats.MonthlyAmountResponse
	24, // 79: stats.StatsService.GetYearlyAmountFailedByMerchant:output_type -> stats.YearlyAmountResponse
	26, // 80: stats.StatsService.GetMonthlyTransactionMethodByMerchantSuccess:output_type -> stats.MonthlyMethodResponse
	28, // 81: stats.StatsService.GetYearlyTransactionMethodByMerchantSuccess:output_type -> stats.YearlyMethodResponse
	26, // 82: stats.StatsService.GetMonthlyTransactionMethodByMerchantFailed:output_type -> stats.MonthlyMethodResponse
	28, // 83: stats.StatsService.GetYearlyTransactionMethodByMerchantFailed:output_type -> stats.YearlyMethodResponse
	48, // [48:84] is the sub-list for method output_type
	12, // [12:48] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_stats_stats_proto_init() }
func file_stats_stats_proto_init() {
	if File_stats_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_stats_proto_rawDesc), len(file_stats_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_stats_proto_goTypes,
		DependencyIndexes: file_stats_stats_proto_depIdxs,
		MessageInfos:      file_stats_stats_proto_msgTypes,
	}.Build()
	File_stats_stats_proto = out.File
	file_stats_stats_proto_goTypes = nil
	file_stats_stats_proto_depIdxs = nil
}
