// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: stats/stats.proto

package stats

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatsService_GetMonthlyTotalPrice_FullMethodName                         = "/stats.StatsService/GetMonthlyTotalPrice"
	StatsService_GetYearlyTotalPrices_FullMethodName                         = "/stats.StatsService/GetYearlyTotalPrices"
	StatsService_GetMonthPrice_FullMethodName                                = "/stats.StatsService/GetMonthPrice"
	StatsService_GetYearPrice_FullMethodName                                 = "/stats.StatsService/GetYearPrice"
	StatsService_GetMonthlyTotalPriceById_FullMethodName                     = "/stats.StatsService/GetMonthlyTotalPriceById"
	StatsService_GetYearlyTotalPricesById_FullMethodName                     = "/stats.StatsService/GetYearlyTotalPricesById"
	StatsService_GetMonthPriceById_FullMethodName                            = "/stats.StatsService/GetMonthPriceById"
	StatsService_GetYearPriceById_FullMethodName                             = "/stats.StatsService/GetYearPriceById"
	StatsService_GetMonthlyTotalPriceByMerchant_FullMethodName               = "/stats.StatsService/GetMonthlyTotalPriceByMerchant"
	StatsService_GetYearlyTotalPricesByMerchant_FullMethodName               = "/stats.StatsService/GetYearlyTotalPricesByMerchant"
	StatsService_GetMonthPriceByMerchant_FullMethodName                      = "/stats.StatsService/GetMonthPriceByMerchant"
	StatsService_GetYearPriceByMerchant_FullMethodName                       = "/stats.StatsService/GetYearPriceByMerchant"
	StatsService_GetMonthlyTotalRevenue_FullMethodName                       = "/stats.StatsService/GetMonthlyTotalRevenue"
	StatsService_GetYearlyTotalRevenue_FullMethodName                        = "/stats.StatsService/GetYearlyTotalRevenue"
	StatsService_GetMonthlyOrder_FullMethodName                              = "/stats.StatsService/GetMonthlyOrder"
	StatsService_GetYearlyOrder_FullMethodName                               = "/stats.StatsService/GetYearlyOrder"
	StatsService_GetMonthlyTotalRevenueByMerchant_FullMethodName             = "/stats.StatsService/GetMonthlyTotalRevenueByMerchant"
	StatsService_GetYearlyTotalRevenueByMerchant_FullMethodName              = "/stats.StatsService/GetYearlyTotalRevenueByMerchant"
	StatsService_GetMonthlyOrderByMerchant_FullMethodName                    = "/stats.StatsService/GetMonthlyOrderByMerchant"
	StatsService_GetYearlyOrderByMerchant_FullMethodName                     = "/stats.StatsService/GetYearlyOrderByMerchant"
	StatsService_GetMonthlyAmountSuccess_FullMethodName                      = "/stats.StatsService/GetMonthlyAmountSuccess"
	StatsService_GetYearlyAmountSuccess_FullMethodName                       = "/stats.StatsService/GetYearlyAmountSuccess"
	StatsService_GetMonthlyAmountFailed_FullMethodName                       = "/stats.StatsService/GetMonthlyAmountFailed"
	StatsService_GetYearlyAmountFailed_FullMethodName                        = "/stats.StatsService/GetYearlyAmountFailed"
	StatsService_GetMonthlyTransactionMethodSuccess_FullMethodName           = "/stats.StatsService/GetMonthlyTransactionMethodSuccess"
	StatsService_GetYearlyTransactionMethodSuccess_FullMethodName            = "/stats.StatsService/GetYearlyTransactionMethodSuccess"
	StatsService_GetMonthlyTransactionMethodFailed_FullMethodName            = "/stats.StatsService/GetMonthlyTransactionMethodFailed"
	StatsService_GetYearlyTransactionMethodFailed_FullMethodName             = "/stats.StatsService/GetYearlyTransactionMethodFailed"
	StatsService_GetMonthlyAmountSuccessByMerchant_FullMethodName            = "/stats.StatsService/GetMonthlyAmountSuccessByMerchant"
	StatsService_GetYearlyAmountSuccessByMerchant_FullMethodName             = "/stats.StatsService/GetYearlyAmountSuccessByMerchant"
	StatsService_GetMonthlyAmountFailedByMerchant_FullMethodName             = "/stats.StatsService/GetMonthlyAmountFailedByMerchant"
	StatsService_GetYearlyAmountFailedByMerchant_FullMethodName              = "/stats.StatsService/GetYearlyAmountFailedByMerchant"
	StatsService_GetMonthlyTransactionMethodByMerchantSuccess_FullMethodName = "/stats.StatsService/GetMonthlyTransactionMethodByMerchantSuccess"
	StatsService_GetYearlyTransactionMethodByMerchantSuccess_FullMethodName  = "/stats.StatsService/GetYearlyTransactionMethodByMerchantSuccess"
	StatsService_GetMonthlyTransactionMethodByMerchantFailed_FullMethodName  = "/stats.StatsService/GetMonthlyTransactionMethodByMerchantFailed"
	StatsService_GetYearlyTransactionMethodByMerchantFailed_FullMethodName   = "/stats.StatsService/GetYearlyTransactionMethodByMerchantFailed"
)

// StatsServiceClient is the client API for StatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatsServiceClient interface {
	// Category Stats
	GetMonthlyTotalPrice(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*MonthlyPriceResponse, error)
	GetYearlyTotalPrices(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*YearlyPriceResponse, error)
	GetMonthPrice(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*MonthlyCategoryResponse, error)
	GetYearPrice(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*YearlyCategoryResponse, error)
	// Category Stats By ID
	GetMonthlyTotalPriceById(ctx context.Context, in *GetStatsByIdRequest, opts ...grpc.CallOption) (*MonthlyPriceResponse, error)
	GetYearlyTotalPricesById(ctx context.Context, in *GetYearlyStatsByIdRequest, opts ...grpc.CallOption) (*YearlyPriceResponse, error)
	GetMonthPriceById(ctx context.Context, in *GetStatsByIdRequest, opts ...grpc.CallOption) (*MonthlyCategoryResponse, error)
	GetYearPriceById(ctx context.Context, in *GetYearlyStatsByIdRequest, opts ...grpc.CallOption) (*YearlyCategoryResponse, error)
	// Category Stats By Merchant
	GetMonthlyTotalPriceByMerchant(ctx context.Context, in *GetStatsByMerchantRequest, opts ...grpc.CallOption) (*MonthlyPriceResponse, error)
	GetYearlyTotalPricesByMerchant(ctx context.Context, in *GetYearlyStatsByMerchantRequest, opts ...grpc.CallOption) (*YearlyPriceResponse, error)
	GetMonthPriceByMerchant(ctx context.Context, in *GetStatsByMerchantRequest, opts ...grpc.CallOption) (*MonthlyCategoryResponse, error)
	GetYearPriceByMerchant(ctx context.Context, in *GetYearlyStatsByMerchantRequest, opts ...grpc.CallOption) (*YearlyCategoryResponse, error)
	// Order Stats
	GetMonthlyTotalRevenue(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*MonthlyRevenueResponse, error)
	GetYearlyTotalRevenue(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*YearlyRevenueResponse, error)
	GetMonthlyOrder(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*MonthlyOrderResponse, error)
	GetYearlyOrder(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*YearlyOrderResponse, error)
	// Order Stats By Merchant
	GetMonthlyTotalRevenueByMerchant(ctx context.Context, in *GetStatsByMerchantRequest, opts ...grpc.CallOption) (*MonthlyRevenueResponse, error)
	GetYearlyTotalRevenueByMerchant(ctx context.Context, in *GetYearlyStatsByMerchantRequest, opts ...grpc.CallOption) (*YearlyRevenueResponse, error)
	GetMonthlyOrderByMerchant(ctx context.Context, in *GetStatsByMerchantRequest, opts ...grpc.CallOption) (*MonthlyOrderResponse, error)
	GetYearlyOrderByMerchant(ctx context.Context, in *GetYearlyStatsByMerchantRequest, opts ...grpc.CallOption) (*YearlyOrderResponse, error)
	// Transaction Stats
	GetMonthlyAmountSuccess(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*MonthlyAmountResponse, error)
	GetYearlyAmountSuccess(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*YearlyAmountResponse, error)
	GetMonthlyAmountFailed(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*MonthlyAmountResponse, error)
	GetYearlyAmountFailed(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*YearlyAmountResponse, error)
	GetMonthlyTransactionMethodSuccess(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*MonthlyMethodResponse, error)
	GetYearlyTransactionMethodSuccess(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*YearlyMethodResponse, error)
	GetMonthlyTransactionMethodFailed(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*MonthlyMethodResponse, error)
	GetYearlyTransactionMethodFailed(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*YearlyMethodResponse, error)
	// Transaction Stats By Merchant
	GetMonthlyAmountSuccessByMerchant(ctx context.Context, in *GetStatsByMerchantRequest, opts ...grpc.CallOption) (*MonthlyAmountResponse, error)
	GetYearlyAmountSuccessByMerchant(ctx context.Context, in *GetYearlyStatsByMerchantRequest, opts ...grpc.CallOption) (*YearlyAmountResponse, error)
	GetMonthlyAmountFailedByMerchant(ctx context.Context, in *GetStatsByMerchantRequest, opts ...grpc.CallOption) (*MonthlyAmountResponse, error)
	GetYearlyAmountFailedByMerchant(ctx context.Context, in *GetYearlyStatsByMerchantRequest, opts ...grpc.CallOption) (*YearlyAmountResponse, error)
	GetMonthlyTransactionMethodByMerchantSuccess(ctx context.Context, in *GetStatsByMerchantRequest, opts ...grpc.CallOption) (*MonthlyMethodResponse, error)
	GetYearlyTransactionMethodByMerchantSuccess(ctx context.Context, in *GetYearlyStatsByMerchantRequest, opts ...grpc.CallOption) (*YearlyMethodResponse, error)
	GetMonthlyTransactionMethodByMerchantFailed(ctx context.Context, in *GetStatsByMerchantRequest, opts ...grpc.CallOption) (*MonthlyMethodResponse, error)
	GetYearlyTransactionMethodByMerchantFailed(ctx context.Context, in *GetYearlyStatsByMerchantRequest, opts ...grpc.CallOption) (*YearlyMethodResponse, error)
}

type statsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsServiceClient(cc grpc.ClientConnInterface) StatsServiceClient {
	return &statsServiceClient{cc}
}

func (c *statsServiceClient) GetMonthlyTotalPrice(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*MonthlyPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyPriceResponse)
	err := c.cc.Invoke(ctx, StatsService_GetMonthlyTotalPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetYearlyTotalPrices(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*YearlyPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearlyPriceResponse)
	err := c.cc.Invoke(ctx, StatsService_GetYearlyTotalPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetMonthPrice(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*MonthlyCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyCategoryResponse)
	err := c.cc.Invoke(ctx, StatsService_GetMonthPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetYearPrice(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*YearlyCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearlyCategoryResponse)
	err := c.cc.Invoke(ctx, StatsService_GetYearPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetMonthlyTotalPriceById(ctx context.Context, in *GetStatsByIdRequest, opts ...grpc.CallOption) (*MonthlyPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyPriceResponse)
	err := c.cc.Invoke(ctx, StatsService_GetMonthlyTotalPriceById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetYearlyTotalPricesById(ctx context.Context, in *GetYearlyStatsByIdRequest, opts ...grpc.CallOption) (*YearlyPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearlyPriceResponse)
	err := c.cc.Invoke(ctx, StatsService_GetYearlyTotalPricesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetMonthPriceById(ctx context.Context, in *GetStatsByIdRequest, opts ...grpc.CallOption) (*MonthlyCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyCategoryResponse)
	err := c.cc.Invoke(ctx, StatsService_GetMonthPriceById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetYearPriceById(ctx context.Context, in *GetYearlyStatsByIdRequest, opts ...grpc.CallOption) (*YearlyCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearlyCategoryResponse)
	err := c.cc.Invoke(ctx, StatsService_GetYearPriceById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetMonthlyTotalPriceByMerchant(ctx context.Context, in *GetStatsByMerchantRequest, opts ...grpc.CallOption) (*MonthlyPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyPriceResponse)
	err := c.cc.Invoke(ctx, StatsService_GetMonthlyTotalPriceByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetYearlyTotalPricesByMerchant(ctx context.Context, in *GetYearlyStatsByMerchantRequest, opts ...grpc.CallOption) (*YearlyPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearlyPriceResponse)
	err := c.cc.Invoke(ctx, StatsService_GetYearlyTotalPricesByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetMonthPriceByMerchant(ctx context.Context, in *GetStatsByMerchantRequest, opts ...grpc.CallOption) (*MonthlyCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyCategoryResponse)
	err := c.cc.Invoke(ctx, StatsService_GetMonthPriceByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetYearPriceByMerchant(ctx context.Context, in *GetYearlyStatsByMerchantRequest, opts ...grpc.CallOption) (*YearlyCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearlyCategoryResponse)
	err := c.cc.Invoke(ctx, StatsService_GetYearPriceByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetMonthlyTotalRevenue(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*MonthlyRevenueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyRevenueResponse)
	err := c.cc.Invoke(ctx, StatsService_GetMonthlyTotalRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetYearlyTotalRevenue(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*YearlyRevenueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearlyRevenueResponse)
	err := c.cc.Invoke(ctx, StatsService_GetYearlyTotalRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetMonthlyOrder(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*MonthlyOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyOrderResponse)
	err := c.cc.Invoke(ctx, StatsService_GetMonthlyOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetYearlyOrder(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*YearlyOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearlyOrderResponse)
	err := c.cc.Invoke(ctx, StatsService_GetYearlyOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetMonthlyTotalRevenueByMerchant(ctx context.Context, in *GetStatsByMerchantRequest, opts ...grpc.CallOption) (*MonthlyRevenueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyRevenueResponse)
	err := c.cc.Invoke(ctx, StatsService_GetMonthlyTotalRevenueByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetYearlyTotalRevenueByMerchant(ctx context.Context, in *GetYearlyStatsByMerchantRequest, opts ...grpc.CallOption) (*YearlyRevenueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearlyRevenueResponse)
	err := c.cc.Invoke(ctx, StatsService_GetYearlyTotalRevenueByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetMonthlyOrderByMerchant(ctx context.Context, in *GetStatsByMerchantRequest, opts ...grpc.CallOption) (*MonthlyOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyOrderResponse)
	err := c.cc.Invoke(ctx, StatsService_GetMonthlyOrderByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetYearlyOrderByMerchant(ctx context.Context, in *GetYearlyStatsByMerchantRequest, opts ...grpc.CallOption) (*YearlyOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearlyOrderResponse)
	err := c.cc.Invoke(ctx, StatsService_GetYearlyOrderByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetMonthlyAmountSuccess(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*MonthlyAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyAmountResponse)
	err := c.cc.Invoke(ctx, StatsService_GetMonthlyAmountSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetYearlyAmountSuccess(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*YearlyAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearlyAmountResponse)
	err := c.cc.Invoke(ctx, StatsService_GetYearlyAmountSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetMonthlyAmountFailed(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*MonthlyAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyAmountResponse)
	err := c.cc.Invoke(ctx, StatsService_GetMonthlyAmountFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetYearlyAmountFailed(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*YearlyAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearlyAmountResponse)
	err := c.cc.Invoke(ctx, StatsService_GetYearlyAmountFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetMonthlyTransactionMethodSuccess(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*MonthlyMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyMethodResponse)
	err := c.cc.Invoke(ctx, StatsService_GetMonthlyTransactionMethodSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetYearlyTransactionMethodSuccess(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*YearlyMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearlyMethodResponse)
	err := c.cc.Invoke(ctx, StatsService_GetYearlyTransactionMethodSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetMonthlyTransactionMethodFailed(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*MonthlyMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyMethodResponse)
	err := c.cc.Invoke(ctx, StatsService_GetMonthlyTransactionMethodFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetYearlyTransactionMethodFailed(ctx context.Context, in *GetYearlyStatsRequest, opts ...grpc.CallOption) (*YearlyMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearlyMethodResponse)
	err := c.cc.Invoke(ctx, StatsService_GetYearlyTransactionMethodFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetMonthlyAmountSuccessByMerchant(ctx context.Context, in *GetStatsByMerchantRequest, opts ...grpc.CallOption) (*MonthlyAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyAmountResponse)
	err := c.cc.Invoke(ctx, StatsService_GetMonthlyAmountSuccessByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetYearlyAmountSuccessByMerchant(ctx context.Context, in *GetYearlyStatsByMerchantRequest, opts ...grpc.CallOption) (*YearlyAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearlyAmountResponse)
	err := c.cc.Invoke(ctx, StatsService_GetYearlyAmountSuccessByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetMonthlyAmountFailedByMerchant(ctx context.Context, in *GetStatsByMerchantRequest, opts ...grpc.CallOption) (*MonthlyAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyAmountResponse)
	err := c.cc.Invoke(ctx, StatsService_GetMonthlyAmountFailedByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetYearlyAmountFailedByMerchant(ctx context.Context, in *GetYearlyStatsByMerchantRequest, opts ...grpc.CallOption) (*YearlyAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearlyAmountResponse)
	err := c.cc.Invoke(ctx, StatsService_GetYearlyAmountFailedByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetMonthlyTransactionMethodByMerchantSuccess(ctx context.Context, in *GetStatsByMerchantRequest, opts ...grpc.CallOption) (*MonthlyMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyMethodResponse)
	err := c.cc.Invoke(ctx, StatsService_GetMonthlyTransactionMethodByMerchantSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetYearlyTransactionMethodByMerchantSuccess(ctx context.Context, in *GetYearlyStatsByMerchantRequest, opts ...grpc.CallOption) (*YearlyMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearlyMethodResponse)
	err := c.cc.Invoke(ctx, StatsService_GetYearlyTransactionMethodByMerchantSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetMonthlyTransactionMethodByMerchantFailed(ctx context.Context, in *GetStatsByMerchantRequest, opts ...grpc.CallOption) (*MonthlyMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyMethodResponse)
	err := c.cc.Invoke(ctx, StatsService_GetMonthlyTransactionMethodByMerchantFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetYearlyTransactionMethodByMerchantFailed(ctx context.Context, in *GetYearlyStatsByMerchantRequest, opts ...grpc.CallOption) (*YearlyMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YearlyMethodResponse)
	err := c.cc.Invoke(ctx, StatsService_GetYearlyTransactionMethodByMerchantFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServiceServer is the server API for StatsService service.
// All implementations must embed UnimplementedStatsServiceServer
// for forward compatibility.
type StatsServiceServer interface {
	// Category Stats
	GetMonthlyTotalPrice(context.Context, *GetStatsRequest) (*MonthlyPriceResponse, error)
	GetYearlyTotalPrices(context.Context, *GetYearlyStatsRequest) (*YearlyPriceResponse, error)
	GetMonthPrice(context.Context, *GetYearlyStatsRequest) (*MonthlyCategoryResponse, error)
	GetYearPrice(context.Context, *GetYearlyStatsRequest) (*YearlyCategoryResponse, error)
	// Category Stats By ID
	GetMonthlyTotalPriceById(context.Context, *GetStatsByIdRequest) (*MonthlyPriceResponse, error)
	GetYearlyTotalPricesById(context.Context, *GetYearlyStatsByIdRequest) (*YearlyPriceResponse, error)
	GetMonthPriceById(context.Context, *GetStatsByIdRequest) (*MonthlyCategoryResponse, error)
	GetYearPriceById(context.Context, *GetYearlyStatsByIdRequest) (*YearlyCategoryResponse, error)
	// Category Stats By Merchant
	GetMonthlyTotalPriceByMerchant(context.Context, *GetStatsByMerchantRequest) (*MonthlyPriceResponse, error)
	GetYearlyTotalPricesByMerchant(context.Context, *GetYearlyStatsByMerchantRequest) (*YearlyPriceResponse, error)
	GetMonthPriceByMerchant(context.Context, *GetStatsByMerchantRequest) (*MonthlyCategoryResponse, error)
	GetYearPriceByMerchant(context.Context, *GetYearlyStatsByMerchantRequest) (*YearlyCategoryResponse, error)
	// Order Stats
	GetMonthlyTotalRevenue(context.Context, *GetStatsRequest) (*MonthlyRevenueResponse, error)
	GetYearlyTotalRevenue(context.Context, *GetYearlyStatsRequest) (*YearlyRevenueResponse, error)
	GetMonthlyOrder(context.Context, *GetYearlyStatsRequest) (*MonthlyOrderResponse, error)
	GetYearlyOrder(context.Context, *GetYearlyStatsRequest) (*YearlyOrderResponse, error)
	// Order Stats By Merchant
	GetMonthlyTotalRevenueByMerchant(context.Context, *GetStatsByMerchantRequest) (*MonthlyRevenueResponse, error)
	GetYearlyTotalRevenueByMerchant(context.Context, *GetYearlyStatsByMerchantRequest) (*YearlyRevenueResponse, error)
	GetMonthlyOrderByMerchant(context.Context, *GetStatsByMerchantRequest) (*MonthlyOrderResponse, error)
	GetYearlyOrderByMerchant(context.Context, *GetYearlyStatsByMerchantRequest) (*YearlyOrderResponse, error)
	// Transaction Stats
	GetMonthlyAmountSuccess(context.Context, *GetStatsRequest) (*MonthlyAmountResponse, error)
	GetYearlyAmountSuccess(context.Context, *GetYearlyStatsRequest) (*YearlyAmountResponse, error)
	GetMonthlyAmountFailed(context.Context, *GetStatsRequest) (*MonthlyAmountResponse, error)
	GetYearlyAmountFailed(context.Context, *GetYearlyStatsRequest) (*YearlyAmountResponse, error)
	GetMonthlyTransactionMethodSuccess(context.Context, *GetStatsRequest) (*MonthlyMethodResponse, error)
	GetYearlyTransactionMethodSuccess(context.Context, *GetYearlyStatsRequest) (*YearlyMethodResponse, error)
	GetMonthlyTransactionMethodFailed(context.Context, *GetStatsRequest) (*MonthlyMethodResponse, error)
	GetYearlyTransactionMethodFailed(context.Context, *GetYearlyStatsRequest) (*YearlyMethodResponse, error)
	// Transaction Stats By Merchant
	GetMonthlyAmountSuccessByMerchant(context.Context, *GetStatsByMerchantRequest) (*MonthlyAmountResponse, error)
	GetYearlyAmountSuccessByMerchant(context.Context, *GetYearlyStatsByMerchantRequest) (*YearlyAmountResponse, error)
	GetMonthlyAmountFailedByMerchant(context.Context, *GetStatsByMerchantRequest) (*MonthlyAmountResponse, error)
	GetYearlyAmountFailedByMerchant(context.Context, *GetYearlyStatsByMerchantRequest) (*YearlyAmountResponse, error)
	GetMonthlyTransactionMethodByMerchantSuccess(context.Context, *GetStatsByMerchantRequest) (*MonthlyMethodResponse, error)
	GetYearlyTransactionMethodByMerchantSuccess(context.Context, *GetYearlyStatsByMerchantRequest) (*YearlyMethodResponse, error)
	GetMonthlyTransactionMethodByMerchantFailed(context.Context, *GetStatsByMerchantRequest) (*MonthlyMethodResponse, error)
	GetYearlyTransactionMethodByMerchantFailed(context.Context, *GetYearlyStatsByMerchantRequest) (*YearlyMethodResponse, error)
	mustEmbedUnimplementedStatsServiceServer()
}

// UnimplementedStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatsServiceServer struct{}

func (UnimplementedStatsServiceServer) GetMonthlyTotalPrice(context.Context, *GetStatsRequest) (*MonthlyPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyTotalPrice not implemented")
}
func (UnimplementedStatsServiceServer) GetYearlyTotalPrices(context.Context, *GetYearlyStatsRequest) (*YearlyPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyTotalPrices not implemented")
}
func (UnimplementedStatsServiceServer) GetMonthPrice(context.Context, *GetYearlyStatsRequest) (*MonthlyCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthPrice not implemented")
}
func (UnimplementedStatsServiceServer) GetYearPrice(context.Context, *GetYearlyStatsRequest) (*YearlyCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearPrice not implemented")
}
func (UnimplementedStatsServiceServer) GetMonthlyTotalPriceById(context.Context, *GetStatsByIdRequest) (*MonthlyPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyTotalPriceById not implemented")
}
func (UnimplementedStatsServiceServer) GetYearlyTotalPricesById(context.Context, *GetYearlyStatsByIdRequest) (*YearlyPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyTotalPricesById not implemented")
}
func (UnimplementedStatsServiceServer) GetMonthPriceById(context.Context, *GetStatsByIdRequest) (*MonthlyCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthPriceById not implemented")
}
func (UnimplementedStatsServiceServer) GetYearPriceById(context.Context, *GetYearlyStatsByIdRequest) (*YearlyCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearPriceById not implemented")
}
func (UnimplementedStatsServiceServer) GetMonthlyTotalPriceByMerchant(context.Context, *GetStatsByMerchantRequest) (*MonthlyPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyTotalPriceByMerchant not implemented")
}
func (UnimplementedStatsServiceServer) GetYearlyTotalPricesByMerchant(context.Context, *GetYearlyStatsByMerchantRequest) (*YearlyPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyTotalPricesByMerchant not implemented")
}
func (UnimplementedStatsServiceServer) GetMonthPriceByMerchant(context.Context, *GetStatsByMerchantRequest) (*MonthlyCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthPriceByMerchant not implemented")
}
func (UnimplementedStatsServiceServer) GetYearPriceByMerchant(context.Context, *GetYearlyStatsByMerchantRequest) (*YearlyCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearPriceByMerchant not implemented")
}
func (UnimplementedStatsServiceServer) GetMonthlyTotalRevenue(context.Context, *GetStatsRequest) (*MonthlyRevenueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyTotalRevenue not implemented")
}
func (UnimplementedStatsServiceServer) GetYearlyTotalRevenue(context.Context, *GetYearlyStatsRequest) (*YearlyRevenueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyTotalRevenue not implemented")
}
func (UnimplementedStatsServiceServer) GetMonthlyOrder(context.Context, *GetYearlyStatsRequest) (*MonthlyOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyOrder not implemented")
}
func (UnimplementedStatsServiceServer) GetYearlyOrder(context.Context, *GetYearlyStatsRequest) (*YearlyOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyOrder not implemented")
}
func (UnimplementedStatsServiceServer) GetMonthlyTotalRevenueByMerchant(context.Context, *GetStatsByMerchantRequest) (*MonthlyRevenueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyTotalRevenueByMerchant not implemented")
}
func (UnimplementedStatsServiceServer) GetYearlyTotalRevenueByMerchant(context.Context, *GetYearlyStatsByMerchantRequest) (*YearlyRevenueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyTotalRevenueByMerchant not implemented")
}
func (UnimplementedStatsServiceServer) GetMonthlyOrderByMerchant(context.Context, *GetStatsByMerchantRequest) (*MonthlyOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyOrderByMerchant not implemented")
}
func (UnimplementedStatsServiceServer) GetYearlyOrderByMerchant(context.Context, *GetYearlyStatsByMerchantRequest) (*YearlyOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyOrderByMerchant not implemented")
}
func (UnimplementedStatsServiceServer) GetMonthlyAmountSuccess(context.Context, *GetStatsRequest) (*MonthlyAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyAmountSuccess not implemented")
}
func (UnimplementedStatsServiceServer) GetYearlyAmountSuccess(context.Context, *GetYearlyStatsRequest) (*YearlyAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyAmountSuccess not implemented")
}
func (UnimplementedStatsServiceServer) GetMonthlyAmountFailed(context.Context, *GetStatsRequest) (*MonthlyAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyAmountFailed not implemented")
}
func (UnimplementedStatsServiceServer) GetYearlyAmountFailed(context.Context, *GetYearlyStatsRequest) (*YearlyAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyAmountFailed not implemented")
}
func (UnimplementedStatsServiceServer) GetMonthlyTransactionMethodSuccess(context.Context, *GetStatsRequest) (*MonthlyMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyTransactionMethodSuccess not implemented")
}
func (UnimplementedStatsServiceServer) GetYearlyTransactionMethodSuccess(context.Context, *GetYearlyStatsRequest) (*YearlyMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyTransactionMethodSuccess not implemented")
}
func (UnimplementedStatsServiceServer) GetMonthlyTransactionMethodFailed(context.Context, *GetStatsRequest) (*MonthlyMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyTransactionMethodFailed not implemented")
}
func (UnimplementedStatsServiceServer) GetYearlyTransactionMethodFailed(context.Context, *GetYearlyStatsRequest) (*YearlyMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyTransactionMethodFailed not implemented")
}
func (UnimplementedStatsServiceServer) GetMonthlyAmountSuccessByMerchant(context.Context, *GetStatsByMerchantRequest) (*MonthlyAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyAmountSuccessByMerchant not implemented")
}
func (UnimplementedStatsServiceServer) GetYearlyAmountSuccessByMerchant(context.Context, *GetYearlyStatsByMerchantRequest) (*YearlyAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyAmountSuccessByMerchant not implemented")
}
func (UnimplementedStatsServiceServer) GetMonthlyAmountFailedByMerchant(context.Context, *GetStatsByMerchantRequest) (*MonthlyAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyAmountFailedByMerchant not implemented")
}
func (UnimplementedStatsServiceServer) GetYearlyAmountFailedByMerchant(context.Context, *GetYearlyStatsByMerchantRequest) (*YearlyAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyAmountFailedByMerchant not implemented")
}
func (UnimplementedStatsServiceServer) GetMonthlyTransactionMethodByMerchantSuccess(context.Context, *GetStatsByMerchantRequest) (*MonthlyMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyTransactionMethodByMerchantSuccess not implemented")
}
func (UnimplementedStatsServiceServer) GetYearlyTransactionMethodByMerchantSuccess(context.Context, *GetYearlyStatsByMerchantRequest) (*YearlyMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyTransactionMethodByMerchantSuccess not implemented")
}
func (UnimplementedStatsServiceServer) GetMonthlyTransactionMethodByMerchantFailed(context.Context, *GetStatsByMerchantRequest) (*MonthlyMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyTransactionMethodByMerchantFailed not implemented")
}
func (UnimplementedStatsServiceServer) GetYearlyTransactionMethodByMerchantFailed(context.Context, *GetYearlyStatsByMerchantRequest) (*YearlyMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetYearlyTransactionMethodByMerchantFailed not implemented")
}
func (UnimplementedStatsServiceServer) mustEmbedUnimplementedStatsServiceServer() {}
func (UnimplementedStatsServiceServer) testEmbeddedByValue()                      {}

// UnsafeStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatsServiceServer will
// result in compilation errors.
type UnsafeStatsServiceServer interface {
	mustEmbedUnimplementedStatsServiceServer()
}

func RegisterStatsServiceServer(s grpc.ServiceRegistrar, srv StatsServiceServer) {
	// If the following call pancis, it indicates UnimplementedStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatsService_ServiceDesc, srv)
}

func _StatsService_GetMonthlyTotalPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetMonthlyTotalPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetMonthlyTotalPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetMonthlyTotalPrice(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetYearlyTotalPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetYearlyTotalPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetYearlyTotalPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetYearlyTotalPrices(ctx, req.(*GetYearlyStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetMonthPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetMonthPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetMonthPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetMonthPrice(ctx, req.(*GetYearlyStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetYearPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetYearPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetYearPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetYearPrice(ctx, req.(*GetYearlyStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetMonthlyTotalPriceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetMonthlyTotalPriceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetMonthlyTotalPriceById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetMonthlyTotalPriceById(ctx, req.(*GetStatsByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetYearlyTotalPricesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetYearlyTotalPricesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetYearlyTotalPricesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetYearlyTotalPricesById(ctx, req.(*GetYearlyStatsByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetMonthPriceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetMonthPriceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetMonthPriceById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetMonthPriceById(ctx, req.(*GetStatsByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetYearPriceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetYearPriceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetYearPriceById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetYearPriceById(ctx, req.(*GetYearlyStatsByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetMonthlyTotalPriceByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsByMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetMonthlyTotalPriceByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetMonthlyTotalPriceByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetMonthlyTotalPriceByMerchant(ctx, req.(*GetStatsByMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetYearlyTotalPricesByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsByMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetYearlyTotalPricesByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetYearlyTotalPricesByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetYearlyTotalPricesByMerchant(ctx, req.(*GetYearlyStatsByMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetMonthPriceByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsByMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetMonthPriceByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetMonthPriceByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetMonthPriceByMerchant(ctx, req.(*GetStatsByMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetYearPriceByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsByMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetYearPriceByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetYearPriceByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetYearPriceByMerchant(ctx, req.(*GetYearlyStatsByMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetMonthlyTotalRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetMonthlyTotalRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetMonthlyTotalRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetMonthlyTotalRevenue(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetYearlyTotalRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetYearlyTotalRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetYearlyTotalRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetYearlyTotalRevenue(ctx, req.(*GetYearlyStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetMonthlyOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetMonthlyOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetMonthlyOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetMonthlyOrder(ctx, req.(*GetYearlyStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetYearlyOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetYearlyOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetYearlyOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetYearlyOrder(ctx, req.(*GetYearlyStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetMonthlyTotalRevenueByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsByMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetMonthlyTotalRevenueByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetMonthlyTotalRevenueByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetMonthlyTotalRevenueByMerchant(ctx, req.(*GetStatsByMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetYearlyTotalRevenueByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsByMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetYearlyTotalRevenueByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetYearlyTotalRevenueByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetYearlyTotalRevenueByMerchant(ctx, req.(*GetYearlyStatsByMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetMonthlyOrderByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsByMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetMonthlyOrderByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetMonthlyOrderByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetMonthlyOrderByMerchant(ctx, req.(*GetStatsByMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetYearlyOrderByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsByMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetYearlyOrderByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetYearlyOrderByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetYearlyOrderByMerchant(ctx, req.(*GetYearlyStatsByMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetMonthlyAmountSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetMonthlyAmountSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetMonthlyAmountSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetMonthlyAmountSuccess(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetYearlyAmountSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetYearlyAmountSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetYearlyAmountSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetYearlyAmountSuccess(ctx, req.(*GetYearlyStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetMonthlyAmountFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetMonthlyAmountFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetMonthlyAmountFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetMonthlyAmountFailed(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetYearlyAmountFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetYearlyAmountFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetYearlyAmountFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetYearlyAmountFailed(ctx, req.(*GetYearlyStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetMonthlyTransactionMethodSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetMonthlyTransactionMethodSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetMonthlyTransactionMethodSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetMonthlyTransactionMethodSuccess(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetYearlyTransactionMethodSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetYearlyTransactionMethodSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetYearlyTransactionMethodSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetYearlyTransactionMethodSuccess(ctx, req.(*GetYearlyStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetMonthlyTransactionMethodFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetMonthlyTransactionMethodFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetMonthlyTransactionMethodFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetMonthlyTransactionMethodFailed(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetYearlyTransactionMethodFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetYearlyTransactionMethodFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetYearlyTransactionMethodFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetYearlyTransactionMethodFailed(ctx, req.(*GetYearlyStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetMonthlyAmountSuccessByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsByMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetMonthlyAmountSuccessByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetMonthlyAmountSuccessByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetMonthlyAmountSuccessByMerchant(ctx, req.(*GetStatsByMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetYearlyAmountSuccessByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsByMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetYearlyAmountSuccessByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetYearlyAmountSuccessByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetYearlyAmountSuccessByMerchant(ctx, req.(*GetYearlyStatsByMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetMonthlyAmountFailedByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsByMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetMonthlyAmountFailedByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetMonthlyAmountFailedByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetMonthlyAmountFailedByMerchant(ctx, req.(*GetStatsByMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetYearlyAmountFailedByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsByMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetYearlyAmountFailedByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetYearlyAmountFailedByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetYearlyAmountFailedByMerchant(ctx, req.(*GetYearlyStatsByMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetMonthlyTransactionMethodByMerchantSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsByMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetMonthlyTransactionMethodByMerchantSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetMonthlyTransactionMethodByMerchantSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetMonthlyTransactionMethodByMerchantSuccess(ctx, req.(*GetStatsByMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetYearlyTransactionMethodByMerchantSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsByMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetYearlyTransactionMethodByMerchantSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetYearlyTransactionMethodByMerchantSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetYearlyTransactionMethodByMerchantSuccess(ctx, req.(*GetYearlyStatsByMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetMonthlyTransactionMethodByMerchantFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsByMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetMonthlyTransactionMethodByMerchantFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetMonthlyTransactionMethodByMerchantFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetMonthlyTransactionMethodByMerchantFailed(ctx, req.(*GetStatsByMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetYearlyTransactionMethodByMerchantFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYearlyStatsByMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetYearlyTransactionMethodByMerchantFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetYearlyTransactionMethodByMerchantFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetYearlyTransactionMethodByMerchantFailed(ctx, req.(*GetYearlyStatsByMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatsService_ServiceDesc is the grpc.ServiceDesc for StatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stats.StatsService",
	HandlerType: (*StatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMonthlyTotalPrice",
			Handler:    _StatsService_GetMonthlyTotalPrice_Handler,
		},
		{
			MethodName: "GetYearlyTotalPrices",
			Handler:    _StatsService_GetYearlyTotalPrices_Handler,
		},
		{
			MethodName: "GetMonthPrice",
			Handler:    _StatsService_GetMonthPrice_Handler,
		},
		{
			MethodName: "GetYearPrice",
			Handler:    _StatsService_GetYearPrice_Handler,
		},
		{
			MethodName: "GetMonthlyTotalPriceById",
			Handler:    _StatsService_GetMonthlyTotalPriceById_Handler,
		},
		{
			MethodName: "GetYearlyTotalPricesById",
			Handler:    _StatsService_GetYearlyTotalPricesById_Handler,
		},
		{
			MethodName: "GetMonthPriceById",
			Handler:    _StatsService_GetMonthPriceById_Handler,
		},
		{
			MethodName: "GetYearPriceById",
			Handler:    _StatsService_GetYearPriceById_Handler,
		},
		{
			MethodName: "GetMonthlyTotalPriceByMerchant",
			Handler:    _StatsService_GetMonthlyTotalPriceByMerchant_Handler,
		},
		{
			MethodName: "GetYearlyTotalPricesByMerchant",
			Handler:    _StatsService_GetYearlyTotalPricesByMerchant_Handler,
		},
		{
			MethodName: "GetMonthPriceByMerchant",
			Handler:    _StatsService_GetMonthPriceByMerchant_Handler,
		},
		{
			MethodName: "GetYearPriceByMerchant",
			Handler:    _StatsService_GetYearPriceByMerchant_Handler,
		},
		{
			MethodName: "GetMonthlyTotalRevenue",
			Handler:    _StatsService_GetMonthlyTotalRevenue_Handler,
		},
		{
			MethodName: "GetYearlyTotalRevenue",
			Handler:    _StatsService_GetYearlyTotalRevenue_Handler,
		},
		{
			MethodName: "GetMonthlyOrder",
			Handler:    _StatsService_GetMonthlyOrder_Handler,
		},
		{
			MethodName: "GetYearlyOrder",
			Handler:    _StatsService_GetYearlyOrder_Handler,
		},
		{
			MethodName: "GetMonthlyTotalRevenueByMerchant",
			Handler:    _StatsService_GetMonthlyTotalRevenueByMerchant_Handler,
		},
		{
			MethodName: "GetYearlyTotalRevenueByMerchant",
			Handler:    _StatsService_GetYearlyTotalRevenueByMerchant_Handler,
		},
		{
			MethodName: "GetMonthlyOrderByMerchant",
			Handler:    _StatsService_GetMonthlyOrderByMerchant_Handler,
		},
		{
			MethodName: "GetYearlyOrderByMerchant",
			Handler:    _StatsService_GetYearlyOrderByMerchant_Handler,
		},
		{
			MethodName: "GetMonthlyAmountSuccess",
			Handler:    _StatsService_GetMonthlyAmountSuccess_Handler,
		},
		{
			MethodName: "GetYearlyAmountSuccess",
			Handler:    _StatsService_GetYearlyAmountSuccess_Handler,
		},
		{
			MethodName: "GetMonthlyAmountFailed",
			Handler:    _StatsService_GetMonthlyAmountFailed_Handler,
		},
		{
			MethodName: "GetYearlyAmountFailed",
			Handler:    _StatsService_GetYearlyAmountFailed_Handler,
		},
		{
			MethodName: "GetMonthlyTransactionMethodSuccess",
			Handler:    _StatsService_GetMonthlyTransactionMethodSuccess_Handler,
		},
		{
			MethodName: "GetYearlyTransactionMethodSuccess",
			Handler:    _StatsService_GetYearlyTransactionMethodSuccess_Handler,
		},
		{
			MethodName: "GetMonthlyTransactionMethodFailed",
			Handler:    _StatsService_GetMonthlyTransactionMethodFailed_Handler,
		},
		{
			MethodName: "GetYearlyTransactionMethodFailed",
			Handler:    _StatsService_GetYearlyTransactionMethodFailed_Handler,
		},
		{
			MethodName: "GetMonthlyAmountSuccessByMerchant",
			Handler:    _StatsService_GetMonthlyAmountSuccessByMerchant_Handler,
		},
		{
			MethodName: "GetYearlyAmountSuccessByMerchant",
			Handler:    _StatsService_GetYearlyAmountSuccessByMerchant_Handler,
		},
		{
			MethodName: "GetMonthlyAmountFailedByMerchant",
			Handler:    _StatsService_GetMonthlyAmountFailedByMerchant_Handler,
		},
		{
			MethodName: "GetYearlyAmountFailedByMerchant",
			Handler:    _StatsService_GetYearlyAmountFailedByMerchant_Handler,
		},
		{
			MethodName: "GetMonthlyTransactionMethodByMerchantSuccess",
			Handler:    _StatsService_GetMonthlyTransactionMethodByMerchantSuccess_Handler,
		},
		{
			MethodName: "GetYearlyTransactionMethodByMerchantSuccess",
			Handler:    _StatsService_GetYearlyTransactionMethodByMerchantSuccess_Handler,
		},
		{
			MethodName: "GetMonthlyTransactionMethodByMerchantFailed",
			Handler:    _StatsService_GetMonthlyTransactionMethodByMerchantFailed_Handler,
		},
		{
			MethodName: "GetYearlyTransactionMethodByMerchantFailed",
			Handler:    _StatsService_GetYearlyTransactionMethodByMerchantFailed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats/stats.proto",
}
