// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: category/category_query.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllCategoryRequest) Reset() {
	*x = FindAllCategoryRequest{}
	mi := &file_category_category_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllCategoryRequest) ProtoMessage() {}

func (x *FindAllCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_category_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllCategoryRequest.ProtoReflect.Descriptor instead.
func (*FindAllCategoryRequest) Descriptor() ([]byte, []int) {
	return file_category_category_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllCategoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllCategoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllCategoryRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

var File_category_category_query_proto protoreflect.FileDescriptor

const file_category_category_query_proto_rawDesc = "" +
	"\n" +
	"\x1dcategory/category_query.proto\x12\x02pb\x1a\x1ecategory/category_common.proto\"a\n" +
	"\x16FindAllCategoryRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search2\xd1\x02\n" +
	"\x14CategoryQueryService\x12H\n" +
	"\aFindAll\x12\x1a.pb.FindAllCategoryRequest\x1a!.pb.ApiResponsePaginationCategory\x12@\n" +
	"\bFindById\x12\x1b.pb.FindByIdCategoryRequest\x1a\x17.pb.ApiResponseCategory\x12U\n" +
	"\fFindByActive\x12\x1a.pb.FindAllCategoryRequest\x1a).pb.ApiResponsePaginationCategoryDeleteAt\x12V\n" +
	"\rFindByTrashed\x12\x1a.pb.FindAllCategoryRequest\x1a).pb.ApiResponsePaginationCategoryDeleteAtB4Z2github.com/MamangRust/monolith-ecommerce-shared/pbb\x06proto3"

var (
	file_category_category_query_proto_rawDescOnce sync.Once
	file_category_category_query_proto_rawDescData []byte
)

func file_category_category_query_proto_rawDescGZIP() []byte {
	file_category_category_query_proto_rawDescOnce.Do(func() {
		file_category_category_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_category_category_query_proto_rawDesc), len(file_category_category_query_proto_rawDesc)))
	})
	return file_category_category_query_proto_rawDescData
}

var file_category_category_query_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_category_category_query_proto_goTypes = []any{
	(*FindAllCategoryRequest)(nil),                // 0: pb.FindAllCategoryRequest
	(*FindByIdCategoryRequest)(nil),               // 1: pb.FindByIdCategoryRequest
	(*ApiResponsePaginationCategory)(nil),         // 2: pb.ApiResponsePaginationCategory
	(*ApiResponseCategory)(nil),                   // 3: pb.ApiResponseCategory
	(*ApiResponsePaginationCategoryDeleteAt)(nil), // 4: pb.ApiResponsePaginationCategoryDeleteAt
}
var file_category_category_query_proto_depIdxs = []int32{
	0, // 0: pb.CategoryQueryService.FindAll:input_type -> pb.FindAllCategoryRequest
	1, // 1: pb.CategoryQueryService.FindById:input_type -> pb.FindByIdCategoryRequest
	0, // 2: pb.CategoryQueryService.FindByActive:input_type -> pb.FindAllCategoryRequest
	0, // 3: pb.CategoryQueryService.FindByTrashed:input_type -> pb.FindAllCategoryRequest
	2, // 4: pb.CategoryQueryService.FindAll:output_type -> pb.ApiResponsePaginationCategory
	3, // 5: pb.CategoryQueryService.FindById:output_type -> pb.ApiResponseCategory
	4, // 6: pb.CategoryQueryService.FindByActive:output_type -> pb.ApiResponsePaginationCategoryDeleteAt
	4, // 7: pb.CategoryQueryService.FindByTrashed:output_type -> pb.ApiResponsePaginationCategoryDeleteAt
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_category_category_query_proto_init() }
func file_category_category_query_proto_init() {
	if File_category_category_query_proto != nil {
		return
	}
	file_category_category_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_category_category_query_proto_rawDesc), len(file_category_category_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_category_category_query_proto_goTypes,
		DependencyIndexes: file_category_category_query_proto_depIdxs,
		MessageInfos:      file_category_category_query_proto_msgTypes,
	}.Build()
	File_category_category_query_proto = out.File
	file_category_category_query_proto_goTypes = nil
	file_category_category_query_proto_depIdxs = nil
}
