// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: order/order_stats.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_order_order_stats_proto protoreflect.FileDescriptor

const file_order_order_stats_proto_rawDesc = "" +
	"\n" +
	"\x17order/order_stats.proto\x12\x02pb\x1a\x18order/order_common.proto2\xf5\x05\n" +
	"\x11OrderStatsService\x12a\n" +
	"\x17FindMonthlyTotalRevenue\x12\x1d.pb.FindYearMonthTotalRevenue\x1a'.pb.ApiResponseOrderMonthlyTotalRevenue\x12Z\n" +
	"\x16FindYearlyTotalRevenue\x12\x18.pb.FindYearTotalRevenue\x1a&.pb.ApiResponseOrderYearlyTotalRevenue\x12u\n" +
	"!FindMonthlyTotalRevenueByMerchant\x12'.pb.FindYearMonthTotalRevenueByMerchant\x1a'.pb.ApiResponseOrderMonthlyTotalRevenue\x12n\n" +
	" FindYearlyTotalRevenueByMerchant\x12\".pb.FindYearTotalRevenueByMerchant\x1a&.pb.ApiResponseOrderYearlyTotalRevenue\x12D\n" +
	"\x12FindMonthlyRevenue\x12\x11.pb.FindYearOrder\x1a\x1b.pb.ApiResponseOrderMonthly\x12B\n" +
	"\x11FindYearlyRevenue\x12\x11.pb.FindYearOrder\x1a\x1a.pb.ApiResponseOrderYearly\x12X\n" +
	"\x1cFindMonthlyRevenueByMerchant\x12\x1b.pb.FindYearOrderByMerchant\x1a\x1b.pb.ApiResponseOrderMonthly\x12V\n" +
	"\x1bFindYearlyRevenueByMerchant\x12\x1b.pb.FindYearOrderByMerchant\x1a\x1a.pb.ApiResponseOrderYearlyB4Z2github.com/MamangRust/monolith-ecommerce-shared/pbb\x06proto3"

var file_order_order_stats_proto_goTypes = []any{
	(*FindYearMonthTotalRevenue)(nil),           // 0: pb.FindYearMonthTotalRevenue
	(*FindYearTotalRevenue)(nil),                // 1: pb.FindYearTotalRevenue
	(*FindYearMonthTotalRevenueByMerchant)(nil), // 2: pb.FindYearMonthTotalRevenueByMerchant
	(*FindYearTotalRevenueByMerchant)(nil),      // 3: pb.FindYearTotalRevenueByMerchant
	(*FindYearOrder)(nil),                       // 4: pb.FindYearOrder
	(*FindYearOrderByMerchant)(nil),             // 5: pb.FindYearOrderByMerchant
	(*ApiResponseOrderMonthlyTotalRevenue)(nil), // 6: pb.ApiResponseOrderMonthlyTotalRevenue
	(*ApiResponseOrderYearlyTotalRevenue)(nil),  // 7: pb.ApiResponseOrderYearlyTotalRevenue
	(*ApiResponseOrderMonthly)(nil),             // 8: pb.ApiResponseOrderMonthly
	(*ApiResponseOrderYearly)(nil),              // 9: pb.ApiResponseOrderYearly
}
var file_order_order_stats_proto_depIdxs = []int32{
	0, // 0: pb.OrderStatsService.FindMonthlyTotalRevenue:input_type -> pb.FindYearMonthTotalRevenue
	1, // 1: pb.OrderStatsService.FindYearlyTotalRevenue:input_type -> pb.FindYearTotalRevenue
	2, // 2: pb.OrderStatsService.FindMonthlyTotalRevenueByMerchant:input_type -> pb.FindYearMonthTotalRevenueByMerchant
	3, // 3: pb.OrderStatsService.FindYearlyTotalRevenueByMerchant:input_type -> pb.FindYearTotalRevenueByMerchant
	4, // 4: pb.OrderStatsService.FindMonthlyRevenue:input_type -> pb.FindYearOrder
	4, // 5: pb.OrderStatsService.FindYearlyRevenue:input_type -> pb.FindYearOrder
	5, // 6: pb.OrderStatsService.FindMonthlyRevenueByMerchant:input_type -> pb.FindYearOrderByMerchant
	5, // 7: pb.OrderStatsService.FindYearlyRevenueByMerchant:input_type -> pb.FindYearOrderByMerchant
	6, // 8: pb.OrderStatsService.FindMonthlyTotalRevenue:output_type -> pb.ApiResponseOrderMonthlyTotalRevenue
	7, // 9: pb.OrderStatsService.FindYearlyTotalRevenue:output_type -> pb.ApiResponseOrderYearlyTotalRevenue
	6, // 10: pb.OrderStatsService.FindMonthlyTotalRevenueByMerchant:output_type -> pb.ApiResponseOrderMonthlyTotalRevenue
	7, // 11: pb.OrderStatsService.FindYearlyTotalRevenueByMerchant:output_type -> pb.ApiResponseOrderYearlyTotalRevenue
	8, // 12: pb.OrderStatsService.FindMonthlyRevenue:output_type -> pb.ApiResponseOrderMonthly
	9, // 13: pb.OrderStatsService.FindYearlyRevenue:output_type -> pb.ApiResponseOrderYearly
	8, // 14: pb.OrderStatsService.FindMonthlyRevenueByMerchant:output_type -> pb.ApiResponseOrderMonthly
	9, // 15: pb.OrderStatsService.FindYearlyRevenueByMerchant:output_type -> pb.ApiResponseOrderYearly
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_order_stats_proto_init() }
func file_order_order_stats_proto_init() {
	if File_order_order_stats_proto != nil {
		return
	}
	file_order_order_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_order_stats_proto_rawDesc), len(file_order_order_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_order_stats_proto_goTypes,
		DependencyIndexes: file_order_order_stats_proto_depIdxs,
	}.Build()
	File_order_order_stats_proto = out.File
	file_order_order_stats_proto_goTypes = nil
	file_order_order_stats_proto_depIdxs = nil
}
