// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: order/order_query.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllOrderRequest) Reset() {
	*x = FindAllOrderRequest{}
	mi := &file_order_order_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllOrderRequest) ProtoMessage() {}

func (x *FindAllOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllOrderRequest.ProtoReflect.Descriptor instead.
func (*FindAllOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_order_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllOrderRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllOrderRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllOrderRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindAllOrderMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	MerchantId    int32                  `protobuf:"varint,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllOrderMerchantRequest) Reset() {
	*x = FindAllOrderMerchantRequest{}
	mi := &file_order_order_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllOrderMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllOrderMerchantRequest) ProtoMessage() {}

func (x *FindAllOrderMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllOrderMerchantRequest.ProtoReflect.Descriptor instead.
func (*FindAllOrderMerchantRequest) Descriptor() ([]byte, []int) {
	return file_order_order_query_proto_rawDescGZIP(), []int{1}
}

func (x *FindAllOrderMerchantRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllOrderMerchantRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllOrderMerchantRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *FindAllOrderMerchantRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

var File_order_order_query_proto protoreflect.FileDescriptor

const file_order_order_query_proto_rawDesc = "" +
	"\n" +
	"\x17order/order_query.proto\x12\x02pb\x1a\x18order/order_common.proto\"^\n" +
	"\x13FindAllOrderRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x87\x01\n" +
	"\x1bFindAllOrderMerchantRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\x05R\n" +
	"merchantId2\xb6\x02\n" +
	"\x11OrderQueryService\x12B\n" +
	"\aFindAll\x12\x17.pb.FindAllOrderRequest\x1a\x1e.pb.ApiResponsePaginationOrder\x12:\n" +
	"\bFindById\x12\x18.pb.FindByIdOrderRequest\x1a\x14.pb.ApiResponseOrder\x12O\n" +
	"\fFindByActive\x12\x17.pb.FindAllOrderRequest\x1a&.pb.ApiResponsePaginationOrderDeleteAt\x12P\n" +
	"\rFindByTrashed\x12\x17.pb.FindAllOrderRequest\x1a&.pb.ApiResponsePaginationOrderDeleteAtB4Z2github.com/MamangRust/monolith-ecommerce-shared/pbb\x06proto3"

var (
	file_order_order_query_proto_rawDescOnce sync.Once
	file_order_order_query_proto_rawDescData []byte
)

func file_order_order_query_proto_rawDescGZIP() []byte {
	file_order_order_query_proto_rawDescOnce.Do(func() {
		file_order_order_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_order_query_proto_rawDesc), len(file_order_order_query_proto_rawDesc)))
	})
	return file_order_order_query_proto_rawDescData
}

var file_order_order_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_order_order_query_proto_goTypes = []any{
	(*FindAllOrderRequest)(nil),                // 0: pb.FindAllOrderRequest
	(*FindAllOrderMerchantRequest)(nil),        // 1: pb.FindAllOrderMerchantRequest
	(*FindByIdOrderRequest)(nil),               // 2: pb.FindByIdOrderRequest
	(*ApiResponsePaginationOrder)(nil),         // 3: pb.ApiResponsePaginationOrder
	(*ApiResponseOrder)(nil),                   // 4: pb.ApiResponseOrder
	(*ApiResponsePaginationOrderDeleteAt)(nil), // 5: pb.ApiResponsePaginationOrderDeleteAt
}
var file_order_order_query_proto_depIdxs = []int32{
	0, // 0: pb.OrderQueryService.FindAll:input_type -> pb.FindAllOrderRequest
	2, // 1: pb.OrderQueryService.FindById:input_type -> pb.FindByIdOrderRequest
	0, // 2: pb.OrderQueryService.FindByActive:input_type -> pb.FindAllOrderRequest
	0, // 3: pb.OrderQueryService.FindByTrashed:input_type -> pb.FindAllOrderRequest
	3, // 4: pb.OrderQueryService.FindAll:output_type -> pb.ApiResponsePaginationOrder
	4, // 5: pb.OrderQueryService.FindById:output_type -> pb.ApiResponseOrder
	5, // 6: pb.OrderQueryService.FindByActive:output_type -> pb.ApiResponsePaginationOrderDeleteAt
	5, // 7: pb.OrderQueryService.FindByTrashed:output_type -> pb.ApiResponsePaginationOrderDeleteAt
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_order_query_proto_init() }
func file_order_order_query_proto_init() {
	if File_order_order_query_proto != nil {
		return
	}
	file_order_order_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_order_query_proto_rawDesc), len(file_order_order_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_order_query_proto_goTypes,
		DependencyIndexes: file_order_order_query_proto_depIdxs,
		MessageInfos:      file_order_order_query_proto_msgTypes,
	}.Build()
	File_order_order_query_proto = out.File
	file_order_order_query_proto_goTypes = nil
	file_order_order_query_proto_depIdxs = nil
}
