// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: transaction/transaction_stats.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_transaction_transaction_stats_proto protoreflect.FileDescriptor

const file_transaction_transaction_stats_proto_rawDesc = "" +
	"\n" +
	"#transaction/transaction_stats.proto\x12\x02pb\x1a$transaction/transaction_common.proto2\x93\a\n" +
	"\x17TransactionStatsService\x12j\n" +
	"\x17GetMonthlyAmountSuccess\x12!.pb.MonthAmountTransactionRequest\x1a,.pb.ApiResponseTransactionMonthAmountSuccess\x12g\n" +
	"\x16GetYearlyAmountSuccess\x12 .pb.YearAmountTransactionRequest\x1a+.pb.ApiResponseTransactionYearAmountSuccess\x12h\n" +
	"\x16GetMonthlyAmountFailed\x12!.pb.MonthAmountTransactionRequest\x1a+.pb.ApiResponseTransactionMonthAmountFailed\x12e\n" +
	"\x15GetYearlyAmountFailed\x12 .pb.YearAmountTransactionRequest\x1a*.pb.ApiResponseTransactionYearAmountFailed\x12u\n" +
	"\"GetMonthlyTransactionMethodSuccess\x12!.pb.MonthMethodTransactionRequest\x1a,.pb.ApiResponseTransactionMonthPaymentMethod\x12r\n" +
	"!GetYearlyTransactionMethodSuccess\x12 .pb.YearMethodTransactionRequest\x1a+.pb.ApiResponseTransactionYearPaymentmethod\x12t\n" +
	"!GetMonthlyTransactionMethodFailed\x12!.pb.MonthMethodTransactionRequest\x1a,.pb.ApiResponseTransactionMonthPaymentMethod\x12q\n" +
	" GetYearlyTransactionMethodFailed\x12 .pb.YearMethodTransactionRequest\x1a+.pb.ApiResponseTransactionYearPaymentmethodB4Z2github.com/MamangRust/microservice-ecommerce-shared/pbb\x06proto3"

var file_transaction_transaction_stats_proto_goTypes = []any{
	(*MonthAmountTransactionRequest)(nil),            // 0: pb.MonthAmountTransactionRequest
	(*YearAmountTransactionRequest)(nil),             // 1: pb.YearAmountTransactionRequest
	(*MonthMethodTransactionRequest)(nil),            // 2: pb.MonthMethodTransactionRequest
	(*YearMethodTransactionRequest)(nil),             // 3: pb.YearMethodTransactionRequest
	(*ApiResponseTransactionMonthAmountSuccess)(nil), // 4: pb.ApiResponseTransactionMonthAmountSuccess
	(*ApiResponseTransactionYearAmountSuccess)(nil),  // 5: pb.ApiResponseTransactionYearAmountSuccess
	(*ApiResponseTransactionMonthAmountFailed)(nil),  // 6: pb.ApiResponseTransactionMonthAmountFailed
	(*ApiResponseTransactionYearAmountFailed)(nil),   // 7: pb.ApiResponseTransactionYearAmountFailed
	(*ApiResponseTransactionMonthPaymentMethod)(nil), // 8: pb.ApiResponseTransactionMonthPaymentMethod
	(*ApiResponseTransactionYearPaymentmethod)(nil),  // 9: pb.ApiResponseTransactionYearPaymentmethod
}
var file_transaction_transaction_stats_proto_depIdxs = []int32{
	0, // 0: pb.TransactionStatsService.GetMonthlyAmountSuccess:input_type -> pb.MonthAmountTransactionRequest
	1, // 1: pb.TransactionStatsService.GetYearlyAmountSuccess:input_type -> pb.YearAmountTransactionRequest
	0, // 2: pb.TransactionStatsService.GetMonthlyAmountFailed:input_type -> pb.MonthAmountTransactionRequest
	1, // 3: pb.TransactionStatsService.GetYearlyAmountFailed:input_type -> pb.YearAmountTransactionRequest
	2, // 4: pb.TransactionStatsService.GetMonthlyTransactionMethodSuccess:input_type -> pb.MonthMethodTransactionRequest
	3, // 5: pb.TransactionStatsService.GetYearlyTransactionMethodSuccess:input_type -> pb.YearMethodTransactionRequest
	2, // 6: pb.TransactionStatsService.GetMonthlyTransactionMethodFailed:input_type -> pb.MonthMethodTransactionRequest
	3, // 7: pb.TransactionStatsService.GetYearlyTransactionMethodFailed:input_type -> pb.YearMethodTransactionRequest
	4, // 8: pb.TransactionStatsService.GetMonthlyAmountSuccess:output_type -> pb.ApiResponseTransactionMonthAmountSuccess
	5, // 9: pb.TransactionStatsService.GetYearlyAmountSuccess:output_type -> pb.ApiResponseTransactionYearAmountSuccess
	6, // 10: pb.TransactionStatsService.GetMonthlyAmountFailed:output_type -> pb.ApiResponseTransactionMonthAmountFailed
	7, // 11: pb.TransactionStatsService.GetYearlyAmountFailed:output_type -> pb.ApiResponseTransactionYearAmountFailed
	8, // 12: pb.TransactionStatsService.GetMonthlyTransactionMethodSuccess:output_type -> pb.ApiResponseTransactionMonthPaymentMethod
	9, // 13: pb.TransactionStatsService.GetYearlyTransactionMethodSuccess:output_type -> pb.ApiResponseTransactionYearPaymentmethod
	8, // 14: pb.TransactionStatsService.GetMonthlyTransactionMethodFailed:output_type -> pb.ApiResponseTransactionMonthPaymentMethod
	9, // 15: pb.TransactionStatsService.GetYearlyTransactionMethodFailed:output_type -> pb.ApiResponseTransactionYearPaymentmethod
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transaction_transaction_stats_proto_init() }
func file_transaction_transaction_stats_proto_init() {
	if File_transaction_transaction_stats_proto != nil {
		return
	}
	file_transaction_transaction_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_transaction_stats_proto_rawDesc), len(file_transaction_transaction_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_transaction_stats_proto_goTypes,
		DependencyIndexes: file_transaction_transaction_stats_proto_depIdxs,
	}.Build()
	File_transaction_transaction_stats_proto = out.File
	file_transaction_transaction_stats_proto_goTypes = nil
	file_transaction_transaction_stats_proto_depIdxs = nil
}
