// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: transaction/transaction_stats_bymerchant.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_transaction_transaction_stats_bymerchant_proto protoreflect.FileDescriptor

const file_transaction_transaction_stats_bymerchant_proto_rawDesc = "" +
	"\n" +
	".transaction/transaction_stats_bymerchant.proto\x12\x02pb\x1a$transaction/transaction_common.proto2\xb1\b\n" +
	"!TransactionStatsByMerchantService\x12|\n" +
	"!GetMonthlyAmountSuccessByMerchant\x12).pb.MonthAmountTransactionMerchantRequest\x1a,.pb.ApiResponseTransactionMonthAmountSuccess\x12y\n" +
	" GetYearlyAmountSuccessByMerchant\x12(.pb.YearAmountTransactionMerchantRequest\x1a+.pb.ApiResponseTransactionYearAmountSuccess\x12z\n" +
	" GetMonthlyAmountFailedByMerchant\x12).pb.MonthAmountTransactionMerchantRequest\x1a+.pb.ApiResponseTransactionMonthAmountFailed\x12w\n" +
	"\x1fGetYearlyAmountFailedByMerchant\x12(.pb.YearAmountTransactionMerchantRequest\x1a*.pb.ApiResponseTransactionYearAmountFailed\x12\x87\x01\n" +
	",GetMonthlyTransactionMethodByMerchantSuccess\x12).pb.MonthMethodTransactionMerchantRequest\x1a,.pb.ApiResponseTransactionMonthPaymentMethod\x12\x84\x01\n" +
	"+GetYearlyTransactionMethodByMerchantSuccess\x12(.pb.YearMethodTransactionMerchantRequest\x1a+.pb.ApiResponseTransactionYearPaymentmethod\x12\x86\x01\n" +
	"+GetMonthlyTransactionMethodByMerchantFailed\x12).pb.MonthMethodTransactionMerchantRequest\x1a,.pb.ApiResponseTransactionMonthPaymentMethod\x12\x83\x01\n" +
	"*GetYearlyTransactionMethodByMerchantFailed\x12(.pb.YearMethodTransactionMerchantRequest\x1a+.pb.ApiResponseTransactionYearPaymentmethodB4Z2github.com/MamangRust/monolith-ecommerce-shared/pbb\x06proto3"

var file_transaction_transaction_stats_bymerchant_proto_goTypes = []any{
	(*MonthAmountTransactionMerchantRequest)(nil),    // 0: pb.MonthAmountTransactionMerchantRequest
	(*YearAmountTransactionMerchantRequest)(nil),     // 1: pb.YearAmountTransactionMerchantRequest
	(*MonthMethodTransactionMerchantRequest)(nil),    // 2: pb.MonthMethodTransactionMerchantRequest
	(*YearMethodTransactionMerchantRequest)(nil),     // 3: pb.YearMethodTransactionMerchantRequest
	(*ApiResponseTransactionMonthAmountSuccess)(nil), // 4: pb.ApiResponseTransactionMonthAmountSuccess
	(*ApiResponseTransactionYearAmountSuccess)(nil),  // 5: pb.ApiResponseTransactionYearAmountSuccess
	(*ApiResponseTransactionMonthAmountFailed)(nil),  // 6: pb.ApiResponseTransactionMonthAmountFailed
	(*ApiResponseTransactionYearAmountFailed)(nil),   // 7: pb.ApiResponseTransactionYearAmountFailed
	(*ApiResponseTransactionMonthPaymentMethod)(nil), // 8: pb.ApiResponseTransactionMonthPaymentMethod
	(*ApiResponseTransactionYearPaymentmethod)(nil),  // 9: pb.ApiResponseTransactionYearPaymentmethod
}
var file_transaction_transaction_stats_bymerchant_proto_depIdxs = []int32{
	0, // 0: pb.TransactionStatsByMerchantService.GetMonthlyAmountSuccessByMerchant:input_type -> pb.MonthAmountTransactionMerchantRequest
	1, // 1: pb.TransactionStatsByMerchantService.GetYearlyAmountSuccessByMerchant:input_type -> pb.YearAmountTransactionMerchantRequest
	0, // 2: pb.TransactionStatsByMerchantService.GetMonthlyAmountFailedByMerchant:input_type -> pb.MonthAmountTransactionMerchantRequest
	1, // 3: pb.TransactionStatsByMerchantService.GetYearlyAmountFailedByMerchant:input_type -> pb.YearAmountTransactionMerchantRequest
	2, // 4: pb.TransactionStatsByMerchantService.GetMonthlyTransactionMethodByMerchantSuccess:input_type -> pb.MonthMethodTransactionMerchantRequest
	3, // 5: pb.TransactionStatsByMerchantService.GetYearlyTransactionMethodByMerchantSuccess:input_type -> pb.YearMethodTransactionMerchantRequest
	2, // 6: pb.TransactionStatsByMerchantService.GetMonthlyTransactionMethodByMerchantFailed:input_type -> pb.MonthMethodTransactionMerchantRequest
	3, // 7: pb.TransactionStatsByMerchantService.GetYearlyTransactionMethodByMerchantFailed:input_type -> pb.YearMethodTransactionMerchantRequest
	4, // 8: pb.TransactionStatsByMerchantService.GetMonthlyAmountSuccessByMerchant:output_type -> pb.ApiResponseTransactionMonthAmountSuccess
	5, // 9: pb.TransactionStatsByMerchantService.GetYearlyAmountSuccessByMerchant:output_type -> pb.ApiResponseTransactionYearAmountSuccess
	6, // 10: pb.TransactionStatsByMerchantService.GetMonthlyAmountFailedByMerchant:output_type -> pb.ApiResponseTransactionMonthAmountFailed
	7, // 11: pb.TransactionStatsByMerchantService.GetYearlyAmountFailedByMerchant:output_type -> pb.ApiResponseTransactionYearAmountFailed
	8, // 12: pb.TransactionStatsByMerchantService.GetMonthlyTransactionMethodByMerchantSuccess:output_type -> pb.ApiResponseTransactionMonthPaymentMethod
	9, // 13: pb.TransactionStatsByMerchantService.GetYearlyTransactionMethodByMerchantSuccess:output_type -> pb.ApiResponseTransactionYearPaymentmethod
	8, // 14: pb.TransactionStatsByMerchantService.GetMonthlyTransactionMethodByMerchantFailed:output_type -> pb.ApiResponseTransactionMonthPaymentMethod
	9, // 15: pb.TransactionStatsByMerchantService.GetYearlyTransactionMethodByMerchantFailed:output_type -> pb.ApiResponseTransactionYearPaymentmethod
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transaction_transaction_stats_bymerchant_proto_init() }
func file_transaction_transaction_stats_bymerchant_proto_init() {
	if File_transaction_transaction_stats_bymerchant_proto != nil {
		return
	}
	file_transaction_transaction_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_transaction_stats_bymerchant_proto_rawDesc), len(file_transaction_transaction_stats_bymerchant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_transaction_stats_bymerchant_proto_goTypes,
		DependencyIndexes: file_transaction_transaction_stats_bymerchant_proto_depIdxs,
	}.Build()
	File_transaction_transaction_stats_bymerchant_proto = out.File
	file_transaction_transaction_stats_bymerchant_proto_goTypes = nil
	file_transaction_transaction_stats_bymerchant_proto_depIdxs = nil
}
